Repository Strategy11/formidable-forms, pull requests merged in 2022-10, with the labels that each got.

#919 Set the global post object when querying for random page to avoid PHP…
  classes/controllers/FrmFormsController.php
Labels: run analysis

#926 fix radio button field style issues
  css/frm_admin.css
Labels: needs qa

#928 Issue 3841
  classes/controllers/FrmFormActionsController.php
  classes/controllers/FrmHooksController.php
  js/formidable_admin.js
Labels: needs qa

#927 replace newline with <br>
  classes/controllers/FrmFormActionsController.php
  classes/controllers/FrmHooksController.php
  tests/emails/test_FrmEmail.php
Labels: needs qa, run analysis

#922 New draggable helper function
  css/frm_admin.css
  js/formidable_admin.js
Labels: needs qa

#930 New filter "frm_rich_text_emails"
  classes/views/frm-form-actions/_email_settings.php
Labels: needs qa, run analysis

#935 No more hooks for issue 3850
  classes/controllers/FrmFormActionsController.php
  classes/controllers/FrmHooksController.php
  classes/models/FrmEmail.php
  tests/emails/test_FrmEmail.php
Labels: run analysis

#892 Replace sortable with draggable
  css/frm_admin.css
  js/formidable_admin.js
Labels: needs qa, run analysis

#936 Prepare for 5.5.2
  classes/helpers/FrmAppHelper.php
  formidable.php
  languages/formidable.pot
  tests/emails/test_FrmEmail.php
  tests/entries/test_FrmShowEntryShortcode.php
Labels: run analysis

#939 Add LIBXML_COMPACT | LIBXML_PARSEHUGE options to loadXML function call
  classes/helpers/FrmXMLHelper.php
Labels: needs qa, run analysis

#940 Drag and drop enhancements
  css/frm_admin.css
  js/formidable_admin.js
Labels: needs qa

#943 Make honeypot field untabbable after first tab press
  js/formidable.js
Labels: needs qa

#948 Stop treating views index with no filtered form ID as full screen
  classes/controllers/FrmAppController.php
  classes/controllers/FrmStylesController.php
  classes/helpers/FrmAppHelper.php
Labels: needs qa

#951 Fix shortcode typo in strpos check when importing views and pages
  classes/helpers/FrmXMLHelper.php
Labels: needs qa

#945 Only append to array, only iterate an array during csv export
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmCSVExportHelper.php
  psalm.xml
Labels: needs qa, run analysis

#949 turn on $br param for wpautop function
  classes/models/FrmEmail.php
  tests/emails/test_FrmEmail.php
Labels: needs qa

#941 Fix text input advanced option button style
  js/formidable_admin.js
Labels: needs qa

#954 Change how the placeholder ul is built when duplicating field groups …
  js/formidable_admin.js
Labels: needs qa

#956 Full screen consistency
  classes/controllers/FrmAppController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmEntriesHelper.php
  classes/helpers/FrmEntriesListHelper.php
  classes/views/frm-entries/list.php
  classes/views/shared/admin-header.php
  css/frm_admin.css
Labels: needs qa, run analysis

#960 Fix entry info when cached
  classes/models/FrmEntry.php
Labels: run analysis
