Repository Strategy11/formidable-forms, pull requests merged in 2022-11, with the labels that each got.

#962 Placeholder icon for google sheets addon
  classes/controllers/FrmFormActionsController.php
  classes/views/frm-form-actions/default_actions.php
Labels: needs qa

#957 Issue 3889
  classes/models/FrmEmail.php
  tests/emails/test_FrmEmail.php
Labels: needs qa

#967 Prepare for 5.5.3.1
  classes/helpers/FrmAppHelper.php
  formidable.php
  languages/formidable.pot
Labels: run analysis

#968 Update stable tag in readme
  readme.txt
Labels: run analysis

#984 Avoid a fatal error if hidden columns are a string
  classes/controllers/FrmEntriesController.php
  classes/controllers/FrmFormsController.php
  tests/entries/test_FrmEntriesController.php
Labels: type: bug

#990 Exit early in handleFieldGroupLayoutOptionClick if there is no select…
  js/formidable_admin.js
Labels: run analysis
