Repository Strategy11/formidable-forms, pull requests merged in 2022-12, with the labels that each got.

#958 Hcaptcha implementation
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmHooksController.php
  classes/controllers/FrmSettingsController.php
  classes/helpers/FrmFieldsHelper.php
  classes/models/FrmField.php
  classes/models/FrmFieldCaptchaSettings.php
  classes/models/FrmSettings.php
  classes/models/fields/FrmFieldCaptcha.php
  classes/views/frm-fields/back-end/field-captcha.php
  classes/views/frm-fields/back-end/settings.php
  classes/views/frm-settings/captcha/captcha.php
  classes/views/frm-settings/captcha/captcha_keys.php
  classes/views/frm-settings/recaptcha.php
  css/frm_admin.css
  images/captcha_not_setup.png
  images/hcaptcha.png
  images/icons.svg
  images/recaptcha_v3.png
  js/formidable.js
  js/formidable_admin.js
  tests/emails/test_FrmEmail.php
  tests/misc/test_FrmAddon.php
Labels: needs qa, run analysis

#997 Prepare for 5.5.4
  classes/helpers/FrmAppHelper.php
  formidable.php
  js/formidable.min.js
  js/formidable_blocks.js
  languages/formidable.pot
Labels: run analysis

#998 Add more backend validation for frm_install and doJsonFetch, remove h…
  classes/controllers/FrmAppController.php
  classes/controllers/FrmApplicationsController.php
  js/admin/dom.js
Labels: needs qa

#1012 Prepare for 5.5.5
  classes/helpers/FrmAppHelper.php
  formidable.php
  languages/formidable.pot
Labels: run analysis

#1006 Issue 3914
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmHooksController.php
Labels: needs qa

#1005 try to get style id from database even if name is numeric
  classes/helpers/FrmXMLHelper.php
  classes/models/FrmDb.php
Labels: needs qa
