Repository Strategy11/formidable-forms, pull requests merged in 2022-08, with the labels that each got.

#836 Update checkUniqueOpt
  .github/workflows/phpcs.yml
  classes/views/frm-fields/single-option.php
  js/formidable_admin.js
Labels: run analysis

#837 Issue 3679
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmHooksController.php
  classes/views/frm-fields/single-option.php
  js/admin/dom.js
  js/formidable_admin.js
Labels: needs qa

#850 Tweaks and clean up
  classes/views/frm-form-actions/_action_inside.php
  css/frm_admin.css
  js/formidable_admin.js
Labels: run analysis

#856 Support frm_param meta value in view import
  classes/helpers/FrmXMLHelper.php
Labels: needs qa, run analysis

#860 Add extra checks for data in actions
  classes/models/FrmFormAction.php
  tests/forms/test_FrmFormAction.php
Labels: needs qa

#858 Add max length PHP validation for Text field
  classes/models/fields/FrmFieldText.php
  classes/views/frm-fields/back-end/max.php
  classes/views/frm-fields/back-end/settings.php
  classes/views/frm-fields/back-end/value-format.php
  js/formidable_admin.js
Labels: needs qa

#866 Applications compatibility fix with wp 5.6
  classes/controllers/FrmAppController.php
  classes/controllers/FrmApplicationsController.php
Labels: needs qa

#862 Fix issues with landing page upgrade tab message not reflecting license
  classes/views/shared/upgrade_overlay.php
  css/frm_admin.css
  js/formidable_admin.js
Labels: needs qa

#867 Prepare for 5.4.4
  classes/helpers/FrmAppHelper.php
  formidable.php
  languages/formidable.pot
Labels: run analysis

#868 Update post parent id if imported page id parent matches
  classes/helpers/FrmXMLHelper.php
Labels: needs qa

#870 Get meta with entry in FrmEntry::destroy function
  classes/models/FrmEntry.php
Labels: needs qa

#871 Avoid empty error pop up when aborting jquery
  js/formidable_admin.js
Labels: needs qa

#872 Add more languages
  classes/helpers/FrmAppHelper.php
Labels: needs qa

#876 Stop disabling summary fields
  css/frm_admin.css
  js/formidable_admin.js
Labels: needs qa, clean up

#881 Prepare for 5.4.5
  classes/helpers/FrmAppHelper.php
  formidable.php
  languages/formidable.pot
Labels: run analysis
