Repository Strategy11/formidable-forms, pull requests merged in 2022-09, with the labels that each got.

#888 New function FrmAppHelper::get_plugins that adds missing file
  classes/controllers/FrmAddonsController.php
  classes/helpers/FrmAppHelper.php
  classes/models/FrmPluginSearch.php
  classes/models/FrmUsage.php
Labels: run analysis

#887 Treat single field in group as selected group for multiselect
  js/formidable_admin.js
Labels: type: enhancement, needs qa

#884 Add form name shortcode to email actions
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmFormsHelper.php
  classes/models/FrmEmail.php
Labels: type: enhancement, needs qa, run analysis

#880 make sure autocomplete option has priority over input shortcode.
  classes/controllers/FrmFieldsController.php
Labels: needs qa

#890 Issue 3798
  css/frm_admin.css
Labels: needs qa

#896 Update readme for 5.5, update since versions for 5.5
  changelog.txt
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmAppHelper.php
  classes/models/FrmEntryMeta.php
  readme.txt
  tests/base/FrmUnitTest.php
Labels: run analysis

#898 Truncate super long entry names
  classes/models/FrmEntryValidate.php
Labels: needs qa

#899 Add image src to exported image field options
  .github/workflows/phpstan.yml
  classes/helpers/FrmXMLHelper.php
  phpstan.neon
  stubs.php
Labels: needs qa, run analysis

#910 Remove font icons from css
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmStylesHelper.php
  css/custom_theme.css.php
Labels: needs qa

#912 Avoid posts page when setting a random page for preview
  classes/controllers/FrmFormsController.php
Labels: run analysis

#914 Prepare for 5.5.1
  formidable.php
  languages/formidable.pot
  package-lock.json
Labels: run analysis
