Repository Strategy11/formidable-forms, pull requests merged in 2023-09, with the labels that each got.

#1283 Prepare for 6.5
  classes/helpers/FrmAppHelper.php
  formidable.php
  languages/formidable.pot
Labels: run analysis

#1286 Issue 4436
  classes/controllers/FrmAppController.php
  classes/controllers/FrmInboxController.php
  classes/views/frm-forms/new-form-overlay.php
  classes/views/frm-forms/new-form-overlay/leave-email.php
  classes/views/inbox/list.php
  css/frm_admin.css
  js/ac.js
  js/formidable_admin.js
Labels: action: needs qa

#1266 Pro issue 4302
  classes/views/frm-forms/new-form-overlay/leave-email.php
  classes/views/inbox/list.php
  js/formidable.js
  stubs.php
Labels: action: needs qa, run analysis

#1294 Apply Stripe PRs 290 and 291
  stripe/controllers/FrmStrpLiteLinkController.php
Labels: run analysis

#1298 Make sure all search terms are found in addon terms during plugin search
  classes/models/FrmPluginSearch.php
Labels: run analysis

#1303 Fix Views page content button size and position
  classes/controllers/FrmAddonsController.php
  classes/views/shared/views-info.php
Labels: run analysis

#1212 Introducing Styling for Dropdown Placeholder Text
  classes/controllers/FrmFieldsController.php
  css/admin/style.css
  css/custom_theme.css.php
  js/admin/style.js
  js/formidable.js
Labels: action: needs qa, run analysis, deploy
