Repository Strategy11/formidable-forms, pull requests merged in 2023-07, with the labels that each got.

#1230 Enhancement of Category Headings Visibility and Search Results
  css/frm_admin.css
  js/formidable_admin.js
Labels: action: needs qa, run analysis, deploy

#1220 Design Enhancements for Field Group Pop-up
  css/frm_admin.css
  js/formidable_admin.js
Labels: action: needs qa, run analysis

#1231 Prevent Form Submission in WP Block Editor
  css/frm_blocks.css
Labels: action: needs qa, run analysis, deploy

#1234 permanently delete trashed form before xml import
  classes/helpers/FrmXMLHelper.php
Labels: run analysis

#1246 Fix Global Variable Issue with Floating Links
  js/formidable_admin.js
  js/packages/floating-links/config.js
Labels: action: needs qa, run analysis
