Repository Strategy11/formidable-forms, pull requests merged in 2023-05, with the labels that each got.

#1183 Fix: Autocomplete Dropdown Cutoff Issue in Embed Modal When Picking Existing Pages
  js/admin/embed.js
Labels: action: needs qa, run analysis, beta deploy

#1150 add 'Select All' button to forms export
  classes/views/xml/import_form.php
  js/formidable_admin.js
Labels: action: needs qa

#1185 Update readme for 6.3
  changelog.txt
  readme.txt
Labels: run analysis

#1190 Prepare for 6.3
  classes/helpers/FrmAppHelper.php
  formidable.php
  js/formidable.min.js
  js/formidable_admin.js
  languages/formidable.pot
Labels: run analysis

#1193 Fix: Remove Extra Whitespace on Admin Page Content for Small Screens
  css/frm_admin.css
Labels: action: needs qa, run analysis, deploy

#1184 Enhance Field Button Width and Standardize Icon Sizes in Builder
  css/frm_admin.css
Labels: action: needs qa, run analysis, deploy

#1192 avoid whitespaces for dropdown field options
  classes/helpers/FrmHtmlHelper.php
  classes/views/frm-fields/front-end/dropdown-field.php
Labels: action: needs qa

#1195 Fix: Resolve overflow issues on add-ons list page for smaller screens
  css/frm_admin.css
Labels: action: needs qa, run analysis, deploy

#1197 Enhanced Placement of Icons in Select Captcha Type Options
  classes/views/frm-settings/captcha/captcha.php
Labels: action: needs qa, run analysis, deploy

#1198 Fix Collapsed Section Styling Issues
  classes/views/frm-forms/add_field.php
  css/frm_admin.css
Labels: action: needs qa, run analysis, deploy

#1157 Add option to open the redirect page in another tab
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmOnSubmitHelper.php
  classes/models/FrmOnSubmitAction.php
  classes/models/FrmSettings.php
  classes/views/frm-settings/messages.php
  js/formidable.js
  tests/forms/test_FrmFormsController.php
Labels: action: needs qa, run analysis

#1206 Add frm_conf_input_backend filter and show password live update JS
  classes/views/frm-forms/add_field.php
  js/formidable_admin.js
Labels: run analysis
