Repository Strategy11/formidable-forms, pull requests merged in 2023-12, with the labels that each got.

#1399 Add left styling rule when auto fold class is not set on body
  classes/controllers/FrmAppController.php
  css/frm_admin.css
Labels: action: needs qa

#1248 In-plugin summary emails
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmCronController.php
  classes/controllers/FrmEmailSummaryController.php
  classes/controllers/FrmHooksController.php
  classes/helpers/FrmEmailSummaryHelper.php
  classes/models/FrmDb.php
  classes/models/FrmEmailMonthly.php
  classes/models/FrmEmailStats.php
  classes/models/FrmEmailSummary.php
  classes/models/FrmEmailYearly.php
  classes/models/FrmInbox.php
  classes/models/FrmMigrate.php
  classes/models/FrmSettings.php
  classes/views/frm-settings/misc.php
  classes/views/summary-emails/base-plain.php
  classes/views/summary-emails/base.php
  classes/views/summary-emails/stats-plain.php
  classes/views/summary-emails/stats.php
  images/chart.png
  images/notice.png
  images/speaker.png
  images/trophy.png
  js/formidable_admin.js
  stripe/helpers/FrmTransLiteAppHelper.php
  stripe/models/FrmTransLitePayment.php
  tests/emails/test_FrmEmailSummaryHelper.php
Labels: action: needs qa, run analysis, deploy

#1413 Pro issue 3967
  classes/models/FrmField.php
  classes/views/frm-fields/back-end/settings.php
Labels: run analysis

#1409 Change the HTML order of previous buttons, add flex styling to submit button container and keep it left using order: -1
  classes/helpers/FrmFormsHelper.php
  css/custom_theme.css.php
Labels: action: needs qa, run analysis

#1419 Resolve Zebra Stripe Styling Issue on Bottom Row of View Entry Tables - Issue #4210
  css/frm_admin.css
Labels: action: needs qa, deploy

#1371 Compliance with White Labeling in Backend
  classes/views/xml/import_form.php
Labels: action: needs qa, run analysis, deploy

#1420 Fix Warning for modal.php Inclusion in Form Templates on QA Upload
  classes/controllers/FrmFormTemplatesController.php
Labels: run analysis

#1402 Avoid permanent deletion of forms from trash list on page refresh after emptying the trash
  classes/controllers/FrmAppController.php
  classes/controllers/FrmFormsController.php
Labels: run analysis

#1364 Fix Column Checkboxes on Form Entries for iPad Landscape
  css/frm_admin.css
Labels: deploy
