Repository Strategy11/formidable-forms, pull requests merged in 2023-03, with the labels that each got.

#1098 Use active form type when searching forms
  classes/helpers/FrmFormsListHelper.php
  classes/views/frm-forms/list.php
Labels: run analysis

#1104 Only show add new entry when pro is installed
  classes/views/frm-entries/list.php
Labels: needs qa

#1103 Remove max width from #frm_publishing button wrapper element
  css/frm_admin.css
Labels: needs qa

#1106 Run frontend editing code from Pro plugin
  classes/controllers/FrmFormsController.php
Labels: needs qa

#1105 overwrite frm_page_container overflow style for translate page
  css/frm_admin.css
Labels: needs qa

#1108 overwrite .columns-2 styles for view page
  classes/controllers/FrmAppController.php
Labels: needs qa

#1111 avoid using ServerSideRender as it is deprecated
  js/formidable_blocks.js
  js/src/form/block.js
Labels: needs qa

#1115 Prepare for 6.1.2
  classes/helpers/FrmAppHelper.php
  formidable.php
  js/formidable_blocks.js
  languages/formidable.pot
Labels: run analysis

#1117 Code/remove-deprecated-functions
  classes/controllers/FrmAppController.php
  classes/controllers/FrmEntriesController.php
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmFormActionsHelper.php
  classes/models/FrmDb.php
  classes/models/FrmForm.php
  classes/models/FrmNotification.php
  deprecated.php
  deprecated/FrmDbDeprecated.php
  deprecated/FrmDeprecated.php
  deprecated/FrmEntryDeprecated.php
  deprecated/FrmEntryFormat.php
  deprecated/FrmEntryMetaDeprecated.php
  deprecated/FrmFieldDeprecated.php
  deprecated/FrmFormDeprecated.php
  phpstan.neon
  phpunit.xml
  stubs.php
Labels: run analysis

#1116 Remove a few stubs we don't need in lite
  stubs.php
Labels: run analysis

#1095 Enable duplication of collapsed sections
  css/frm_admin.css
  js/formidable_admin.js
Labels: needs qa, run analysis

#1120 Skip any shortcode option that uses =0
  classes/helpers/FrmFieldsHelper.php
Labels: needs qa, run analysis

#1122 Restore some deprecated functions used in addons
  classes/controllers/FrmAppController.php
  classes/helpers/FrmFieldsHelper.php
  classes/models/FrmForm.php
  deprecated/FrmDeprecated.php
Labels: run analysis

#1121 Support 0 for to value for human time diff function
  classes/helpers/FrmAppHelper.php
  tests/misc/test_FrmAppHelper.php
Labels: run analysis

#1062 append template search results after categories list
  js/formidable_admin.js
Labels: needs qa

#1130 Use checkbox role for multiselect buttons and add aria checked attribute
  js/admin/dom.js
Labels: action: needs qa, run analysis
