Repository Strategy11/formidable-forms, pull requests merged in 2023-08, with the labels that each got.

#1199 Enhancing Accessibility and Keyboard Navigation for Radio Buttons and Checkboxes
  classes/controllers/FrmFieldsController.php
  classes/models/FrmFieldFormHtml.php
  classes/models/fields/FrmFieldType.php
  tests/fields/test_FrmFieldFormHtml.php
Labels: action: needs qa, run analysis, deploy

#1253 Change modal in-product education link
  classes/controllers/FrmSimpleBlocksController.php
Labels: run analysis

#1249 Addition of Entry Navigation Buttons on the "View Entry" Page
  classes/views/frm-entries/show.php
Labels: action: needs qa, run analysis, deploy

#1241 Required for Date calculation
  .gitignore
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/views/frm-fields/back-end/inline-modal.php
  formidable.php
  js/admin/dom.js
  js/formidable_admin.js
Labels: run analysis, deploy

#1250 Added Footer Links for Improved User Accessibility
  classes/controllers/FrmAppController.php
  classes/controllers/FrmHooksController.php
  classes/views/shared/admin-footer-links.php
  css/frm_admin.css
Labels: action: needs qa, run analysis, deploy

#1255 Prepare for 6.4.1
  classes/controllers/FrmAppController.php
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmOnSubmitHelper.php
  classes/models/FrmFieldFormHtml.php
  classes/views/frm-entries/show.php
  js/admin/dom.js
  js/formidable_admin.js
  languages/formidable.pot
Labels: run analysis

#1257 Use a couple green links
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmAppController.php
Labels: run analysis

#1258 Add phpcs check for php 5.6 and 8.1
  .github/workflows/phpcs.yml
Labels: run analysis

#1259 Add upsell placeholder for Download as PDF
  classes/controllers/FrmAddonsController.php
  classes/helpers/FrmEntriesHelper.php
Labels: run analysis

#1237 Entry statuses
  classes/controllers/FrmEntriesController.php
  classes/controllers/FrmFormActionsController.php
  classes/helpers/FrmCSVExportHelper.php
  classes/helpers/FrmEntriesHelper.php
  classes/helpers/FrmEntriesListHelper.php
  classes/models/FrmEntry.php
  classes/views/frm-entries/_sidebar-shared-pub.php
  css/frm_admin.css
  images/icons.svg
  tests/misc/test_FrmCSVExportHelper.php
Labels: action: needs qa, run analysis

#1262 save and reload fix when form is submited via ajax
  js/formidable_admin.js
Labels: action: needs qa

#1265 Enhancing Field Settings Accessibility
  .github/workflows/phpcs.yml
  classes/views/frm-fields/back-end/field-description.php
  classes/views/frm-fields/back-end/settings.php
  classes/views/frm-fields/back-end/value-format.php
  css/frm_admin.css
  js/formidable_admin.js
Labels: action: needs qa, run analysis

#1270 Avoid automatic conversion of false to array when saving styles
  classes/controllers/FrmStylesController.php
Labels: run analysis

#1268 Enhanced Compliance with White Labeling Settings in Admin Floating and Footer Links
  .github/workflows/phpcs.yml
  classes/controllers/FrmAppController.php
  classes/helpers/FrmAppHelper.php
Labels: run analysis, deploy
