Repository Strategy11/formidable-forms, pull requests merged in 2023-02, with the labels that each got.

#1048 Prepare for 5.5.7
  classes/helpers/FrmAppHelper.php
  formidable.php
  languages/formidable.pot
Labels: run analysis

#1045 Add new admin toggle element
  classes/controllers/FrmAppController.php
  classes/helpers/FrmHtmlHelper.php
  classes/views/frm-form-actions/form_action.php
  classes/views/shared/mb_adv_info.php
  classes/views/shared/toggle.php
  css/frm_admin.css
  js/admin/settings.js
Labels: needs qa

#1049 Fix broken auto scroll in form builder with scroll bars
  js/formidable_admin.js
Labels: needs qa

#1055 Hide the WP admin menu and toolbar on full screen pages
  classes/controllers/FrmAppController.php
  css/frm_admin.css
Labels: needs qa

#1053 Add more sanitizing to styler colors
  classes/controllers/FrmAppController.php
  classes/helpers/FrmHtmlHelper.php
  classes/models/FrmStyle.php
  classes/views/shared/toggle.php
  psalm.xml
  tests/styles/test_FrmStyle.php
Labels: needs qa, run analysis

#1033 On submit action
  .github/workflows/qadelete.yml
  .github/workflows/qadeploy.yml
  classes/controllers/FrmFormActionsController.php
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmOnSubmitHelper.php
  classes/helpers/FrmTipsHelper.php
  classes/models/FrmFormAction.php
  classes/models/FrmOnSubmitAction.php
  classes/views/frm-form-actions/_action_icon.php
  classes/views/frm-form-actions/form_action.php
  classes/views/frm-form-actions/on_submit_settings.php
  classes/views/frm-forms/settings-advanced.php
  css/frm_admin.css
  images/icons.svg
  js/admin/dom.js
  js/admin/style.js
  js/formidable.js
  js/formidable_admin.js
  stubs.php
  tests/forms/test_FrmFormsController.php
Labels: needs qa, run analysis

#1067 Prepare for 6.0
  classes/controllers/FrmAppController.php
  classes/controllers/FrmStylesController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFormsListHelper.php
  classes/helpers/FrmHtmlHelper.php
  classes/helpers/FrmStylesCardHelper.php
  classes/helpers/FrmStylesHelper.php
  classes/helpers/FrmStylesPreviewHelper.php
  classes/models/FrmApplicationTemplate.php
  classes/models/FrmFieldCaptchaSettings.php
  classes/models/FrmForm.php
  classes/models/FrmFormApi.php
  classes/models/FrmSettings.php
  classes/models/FrmStyleApi.php
  classes/models/fields/FrmFieldCaptcha.php
  classes/models/fields/FrmFieldTextarea.php
  classes/models/fields/FrmFieldType.php
  classes/views/styles/_style-preview-container.php
  formidable.php
  js/admin/dom.js
  js/formidable.js
  js/formidable.min.js
  languages/formidable.pot
Labels: run analysis

#1069 Avoid changing the label position container classes if a field does not use the default
  classes/helpers/FrmStylesPreviewHelper.php
  js/admin/style.js
Labels: needs qa

#1071 Fix PHP 8.2 notices
  classes/controllers/FrmFormsController.php
  classes/models/FrmSettings.php
  classes/views/frm-forms/settings-advanced.php
Labels: run analysis

#1079 Apply frm_success_filter for confirmation actions
  classes/controllers/FrmFormsController.php
Labels: run analysis

#1050 remove default limit on the number of actions triggered
  classes/models/FrmFormAction.php
Labels: needs qa, run analysis

#1082 Fix confirmation update message doesn't work
  classes/controllers/FrmFormsController.php
Labels: run analysis

#1084 Prepare for 6.1
  classes/helpers/FrmAppHelper.php
  formidable.php
  languages/formidable.pot
  tests/misc/test_FrmAppController.php
Labels: run analysis

#1090 Let the pro version use the run_on_submit_actions function
  classes/controllers/FrmFormsController.php
Labels: run analysis

#1091 Fix confirmation action is forced to message
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmOnSubmitHelper.php
  tests/forms/test_FrmFormsController.php
Labels: run analysis

#1093 Pass the event name for redirects too
  classes/controllers/FrmFormsController.php
Labels: run analysis

#1086 add right margin to fields box
  css/frm_admin.css
Labels: needs qa

#1094 Release/v6.1.1
  classes/controllers/FrmAppController.php
  classes/controllers/FrmSettingsController.php
  classes/controllers/FrmStylesController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmStylesHelper.php
  classes/views/frm-forms/multiselect-accessibility.php
  classes/views/frm-settings/recaptcha.php
  classes/views/styles/_upsell-multiple-styles.php
  classes/views/styles/header-buttons.php
  formidable.php
  languages/formidable.pot
  readme.txt
Labels: run analysis
