Repository Strategy11/formidable-forms, pull requests merged in 2023-11, with the labels that each got.

#1347 Fix Footer Misplacement on Initial Page View
  classes/views/shared/admin-footer-links.php
  css/frm_admin.css
  js/formidable_admin.js
Labels: action: needs qa, run analysis, deploy

#1073 Update lite so Pro can adjust entry search queries to include repeaters
  classes/helpers/FrmEntriesListHelper.php
Labels: run analysis

#1362 Update readme for v6.5.4
  changelog.txt
  readme.txt
Labels: run analysis

#1363 Prepare for 6.5.4
  classes/helpers/FrmAppHelper.php
  formidable.php
  js/formidable.min.js
  languages/formidable.pot
Labels: run analysis

#1346 Introduce bottom banner for keyboard command guidance
  classes/helpers/FrmAppHelper.php
  css/frm_admin.css
  js/formidable_admin.js
Labels: action: needs qa, run analysis, deploy

#1367 Enable submit button on bf cache
  js/formidable.js
Labels: action: needs qa

#1368 Address UI Enhancements and Inconsistencies
  css/frm_admin.css
Labels: action: needs qa, deploy

#1372 Stop adding aria-required to role="group" and add aria-required to th…
  classes/models/FrmFieldFormHtml.php
  classes/views/frm-fields/front-end/checkbox-field.php
Labels: action: needs qa, run analysis

#1377 Add screen reader text for more options dropdown toggles
  classes/views/frm-forms/add_field.php
  js/formidable_admin.js
Labels: action: needs qa

#1387 Add composite indexes for entries tables
  classes/helpers/FrmAppHelper.php
  classes/models/FrmMigrate.php
Labels: action: needs qa

#1386 Add a test flag for stripe lite payments
  stripe/controllers/FrmStrpLiteEventsController.php
  stripe/controllers/FrmStrpLiteLinkController.php
  stripe/controllers/FrmTransLiteAppController.php
  stripe/controllers/FrmTransLiteHooksController.php
  stripe/controllers/FrmTransLiteListsController.php
  stripe/helpers/FrmStrpLiteSubscriptionHelper.php
  stripe/helpers/FrmTransLiteAppHelper.php
  stripe/helpers/FrmTransLiteListHelper.php
  stripe/models/FrmTransLiteDb.php
  stripe/models/FrmTransLitePayment.php
  stripe/models/FrmTransLiteSubscription.php
  stripe/views/payments/show.php
  stripe/views/subscriptions/show.php
Labels: action: needs qa

#1398 Prepare for 6.6
  bin/zip-plugin.sh
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmEntriesHelper.php
  classes/helpers/FrmEntriesListHelper.php
  classes/models/FrmEntryValidate.php
  classes/models/FrmMigrate.php
  formidable.php
  js/formidable.min.js
  languages/formidable.pot
  stripe/helpers/FrmTransLiteAppHelper.php
  stripe/helpers/FrmTransLiteListHelper.php
  stripe/models/FrmTransLitePayment.php
  stripe/models/FrmTransLiteSubscription.php
Labels: run analysis

#1390 Reset 'max' option when switching paragraph field type to others
  classes/models/FrmForm.php
Labels: run analysis, deploy

#1395 Fix Pirate forms importer style
  css/frm_admin.css
Labels: action: needs qa
