Repository Strategy11/formidable-forms, pull requests merged in 2023-10, with the labels that each got.

#1310 Apply Stripe fix 298
  stripe/controllers/FrmStrpLiteAppController.php
  stripe/controllers/FrmStrpLiteHooksController.php
  stripe/controllers/FrmStrpLiteLinkController.php
  stripe/controllers/FrmTransLiteActionsController.php
  stripe/helpers/FrmStrpLiteUrlParamHelper.php
  stripe/models/FrmStrpLiteAuth.php
  tests/misc/test_FrmSerializedStringParserHelper.php
Labels: run analysis

#1311 Fix partial phrase
  classes/controllers/FrmAppController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmTipsHelper.php
  classes/views/shared/upgrade_overlay.php
  js/formidable_admin.js
Labels: run analysis

#1278 Form abandonment settings placeholder
  classes/controllers/FrmFormsController.php
  images/icons.svg
  images/screenshots/abandonment.png
Labels: action: needs qa, run analysis

#1299 Hide honeypot using overflow and randomize class and name
  classes/models/FrmHoneypot.php
  css/custom_theme.css.php
  css/frm_grids.css
  js/formidable.js
Labels: action: needs qa

#1318 Prepare for 6.5.1
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmTipsHelper.php
  formidable.php
  js/admin/style.js
  js/formidable.js
  js/formidable.min.js
  languages/formidable.pot
  stripe/controllers/FrmStrpLiteAppController.php
  stripe/controllers/FrmTransLiteActionsController.php
  stripe/helpers/FrmStrpLiteSubscriptionHelper.php
  stripe/helpers/FrmStrpLiteUrlParamHelper.php
  stripe/helpers/FrmTransLiteAppHelper.php
  stripe/models/FrmStrpLiteAuth.php
Labels: run analysis

#1297 delete all entries modal confirmation
  classes/helpers/FrmEntriesListHelper.php
  classes/helpers/FrmListHelper.php
  css/frm_admin.css
  js/formidable_admin.js
Labels: action: needs qa, run analysis

#1327 Prepare for 6.5.2
  classes/helpers/FrmAppHelper.php
  formidable.php
  languages/formidable.pot
Labels: run analysis

#1322 form preview - block theme padding
  classes/controllers/FrmFormsController.php
Labels: action: needs qa

#1337 Stop showing the add new entry button without permissions to add entries
  classes/views/frm-entries/list.php
Labels: action: needs qa

#1343 Add payment refunded action event trigger type
  stripe/controllers/FrmTransLiteActionsController.php
Labels: action: needs qa

#1354 Update since versions
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmCurrencyHelper.php
  classes/helpers/FrmEntriesHelper.php
  classes/views/frm-form-actions/default_actions.php
  formidable.php
  js/formidable.min.js
  languages/formidable.pot
  stripe/controllers/FrmStrpLiteActionsController.php
  stripe/models/FrmTransLiteDb.php
Labels: run analysis

#1333 Remove unconditional view permission set from global settings
  classes/helpers/FrmAppHelper.php
Labels: run analysis

#1348 Fix: Display "Add Fields Here" Message After Deleting All Fields
  js/formidable_admin.js
Labels: action: needs qa, run analysis, deploy

#1342 Fix Vertical Centering of Dropdown Arrows for All Themes
  css/custom_theme.css.php
Labels: action: needs qa, deploy

#1349 Fix: Resolve Overlapping Issue After Deleting a Section in Form Builder
  css/frm_admin.css
Labels: action: needs qa, deploy

#1357 Force truncate for strings way over the limit with no spaces
  classes/helpers/FrmAppHelper.php
  tests/misc/test_FrmAppHelper.php
Labels: action: needs qa
