Repository Strategy11/formidable-forms, pull requests merged in 2023-01, with the labels that each got.

#1021 exclude repeaters from exportable forms list
  classes/controllers/FrmXMLController.php
Labels: needs qa, run analysis

#1017 Logic styling
  css/frm_admin.css
Labels: needs qa

#1013 Add upgrade tip for ACF addon
  classes/helpers/FrmTipsHelper.php
Labels: needs qa

#1023 Prevent both radio buttons from being selected in sample form
  classes/views/styles/_sample_form.php
Labels: type: bug, needs qa

#1001 update default rootline size
  classes/models/FrmStyle.php
Labels: needs qa

#1027 Prepare for 5.5.6
  classes/helpers/FrmAppHelper.php
  formidable.php
  languages/formidable.pot
Labels: run analysis

#1029 Add a new FrmStylesCardHelper class, add back FrmStyleApi and unit te…
  classes/controllers/FrmHooksController.php
  classes/controllers/FrmStylesController.php
  classes/helpers/FrmStylesCardHelper.php
  classes/helpers/FrmStylesHelper.php
  classes/helpers/FrmStylesPreviewHelper.php
  classes/models/FrmStyleApi.php
  classes/views/styles/_custom-style-card.php
  classes/views/styles/_style-preview-container.php
  classes/views/styles/_styles-list.php
  css/admin/style.css
  js/admin/style.js
  tests/styles/test_FrmStyleApi.php
Labels: in progress

#1014 On submit action
  .github/workflows/qadelete.yml
  .github/workflows/qadeploy.yml
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmOnSubmitHelper.php
  classes/helpers/FrmTipsHelper.php
  classes/models/FrmOnSubmitAction.php
  classes/views/frm-form-actions/on_submit_settings.php
  classes/views/frm-forms/settings-advanced.php
  css/frm_admin.css
  images/icons.svg
Labels: needs qa, run analysis

#1019 Replace Rich text fields placeholder setting field with RTE
  classes/models/fields/FrmFieldTextarea.php
  classes/models/fields/FrmFieldType.php
  classes/views/frm-fields/back-end/default-value-field.php
  classes/views/frm-fields/back-end/default-value-setting.php
  classes/views/frm-fields/back-end/settings.php
  classes/views/frm-fields/back-end/textarea-default-value-field.php
Labels: needs qa

#1035 remove repeaters from exportable forms only for xml export
  classes/controllers/FrmXMLController.php
  classes/views/xml/import_form.php
  js/formidable_admin.js
  package-lock.json
Labels: needs qa

#1044 fallback to textarea for rte default value field if pro is <= 5.5.6
  classes/models/fields/FrmFieldType.php
  classes/views/frm-fields/back-end/textarea-default-value-field.php
Labels: run analysis
