Repository Strategy11/formidable-forms, pull requests merged in 2023-04, with the labels that each got.

#1132 Apply frm_redirect_url filter before checking invalid action
  classes/controllers/FrmFormsController.php
Labels: action: needs qa

#1131 Add submit with ajax into Lite
  classes/controllers/FrmEntriesAJAXSubmitController.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmHooksController.php
  classes/helpers/FrmFormsHelper.php
  classes/models/FrmForm.php
  classes/models/FrmFormState.php
  classes/views/frm-entries/form.php
  classes/views/frm-forms/settings-advanced.php
  tests/entries/test_FrmEntriesController.php
Labels: action: needs qa, run analysis

#1146 Fix PayPal action redirecting to a blank page
  classes/controllers/FrmFormsController.php
  tests/forms/test_FrmFormsController.php
Labels: action: needs qa

#1148 Prepare for 6.2.2
  changelog.txt
  classes/helpers/FrmAppHelper.php
  formidable.php
  languages/formidable.pot
  readme.txt
Labels: run analysis

#1151 Fix common XML import issues
  classes/helpers/FrmXMLHelper.php
  tests/xml/test_FrmXMLHelper.php
Labels: action: needs qa

#1158 Remove moveTopBanner function
  js/formidable_admin.js
Labels: action: needs qa

#1163 Fix woocommerce conflict in one place
  classes/controllers/FrmEntriesAJAXSubmitController.php
Labels: action: needs qa

#1164 Prepare for 6.2.3
  changelog.txt
  classes/controllers/FrmStylesController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmXMLHelper.php
  classes/models/FrmStyle.php
  formidable.php
  languages/formidable.pot
  package.json
  readme.txt
Labels: run analysis

#1168 Improve Readability of Import XML Error Messages
  classes/helpers/FrmXMLHelper.php
Labels: action: needs qa, run analysis

#1167 Add Dismissible Warning Message Functionality
  classes/controllers/FrmAppController.php
  classes/helpers/FrmAppHelper.php
  classes/views/shared/errors.php
  css/frm_admin.css
  js/formidable_admin.js
  tests/misc/test_FrmAppHelper.php
  tests/misc/test_FrmAppHeperAjax.php
Labels: action: needs qa, run analysis

#1169 Fix: Dark text on Repeater buttons in Gutenberg block preview
  css/frm_blocks.css
Labels: action: needs qa, run analysis

#1177 Fix a typo on warning comment
  classes/controllers/FrmAppController.php
Labels: clean up

#1174 Fix Confirmation actions don't enforce sanitize_url option in shortcodes
  classes/models/FrmForm.php
  classes/models/FrmOnSubmitAction.php
  js/formidable_admin.js
  tests/forms/test_FrmOnSubmitAction.php
Labels: run analysis

#1178 Enhance error message for missing DOMDocument during XML import
  classes/helpers/FrmXMLHelper.php
Labels: run analysis

#1179 Prevent Dragging of Disabled Field Types
  js/formidable_admin.js
Labels: action: needs qa, run analysis

#1144 support custom validity message
  js/formidable.js
  js/formidable_admin.js
  package-lock.json
  package.json
Labels: action: needs qa

#1172 Refined Embed Modal Footer Styles
  css/frm_admin.css
  tests/entries/test_FrmEntriesListHelper.php
Labels: action: needs qa, run analysis
