Repository Strategy11/formidable-forms, pull requests merged in 2023-06, with the labels that each got.

#1201 Remove Back Button from 'Leave your email address' Modal
  js/formidable_admin.js
Labels: action: needs qa, run analysis, deploy

#1216 Avoid PHP Notice that get_current_screen is called incorrectly when u…
  classes/controllers/FrmEntriesAJAXSubmitController.php
Labels: action: needs qa

#1214 Fix PHP 8.2 deprecations
  tests/base/FrmAjaxUnitTest.php
  tests/base/FrmUnitTest.php
  tests/base/frm_factory.php
Labels: run analysis

#1218 remove crons when lite is deactivated
  classes/controllers/FrmCronController.php
  formidable.php
Labels: run analysis

#1219 make sure param to FrmHtmlHelper::echo_dropdown_option is always boolean
  classes/views/frm-fields/front-end/dropdown-field.php
Labels: action: needs qa, run analysis

#1217 Add a modal link in the blocks
  classes/controllers/FrmSimpleBlocksController.php
  images/modal.png
  js/formidable_blocks.js
  js/src/blocks.js
  js/src/form/calculator.js
  js/src/form/modal.js
Labels: deploy

#1213 use admin_enqueue_scripts hook instead of admin_init
  classes/controllers/FrmAppController.php
  classes/controllers/FrmHooksController.php
Labels: action: needs qa

#1196 Surveys Issue 190 - scale display options core update
  .github/workflows/psalm.yml
  classes/helpers/FrmFieldsHelper.php
  css/_single_theme.css.php
  css/custom_theme.css.php
  js/formidable_admin.js
Labels: run analysis, beta deploy, ready to merge

#1226 trim captcha secrets before save
  classes/models/FrmSettings.php
Labels: action: needs qa

#1227 Resolved JavaScript Errors Triggered by Rapid Preview Dropdown Interactions
  classes/views/frm-forms/_publish_box.php
  js/formidable_admin.js
Labels: action: needs qa, run analysis

#1194 Introduce Floating Links in the Formidable Admin Panel
  classes/controllers/FrmAppController.php
  css/packages/s11-floating-links.css
  js/packages/floating-links/config.js
  js/packages/floating-links/s11-floating-links.js
Labels: type: enhancement, action: needs qa, run analysis, action: needs tests, deploy
