Repository Strategy11/formidable-forms, pull requests merged in 2024-11, with the labels that each got.

#2080 Exclude invalid applications on applications page
  classes/controllers/FrmApplicationsController.php
  classes/models/FrmApplicationTemplate.php
  classes/models/FrmStyle.php
Labels: run analysis, run tests

#2069 Make field options grid clickable on mobile(iphone)
  css/custom_theme.css.php
Labels: run analysis, deploy, run tests

#2079 Enhance UI/UX of Application cards
  css/admin/applications.css
  js/admin/applications.js
Labels: run analysis, run tests

#2082 center form fix
  classes/views/styles/_general.php
Labels: run analysis, run tests

#2083 Fix test to handle dynamic h1 text on formidableforms.com
  tests/cypress/e2e/Forms/formPageDataValidation.cy.js
Labels: run analysis, run tests

#2078 Make implode code safer
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/models/fields/FrmFieldType.php
Labels: run analysis, run tests

#2086 Stop showing onboarding inbox item after visiting onboarding page or …
  classes/controllers/FrmInboxController.php
  classes/controllers/FrmOnboardingWizardController.php
Labels: run analysis, run tests

#1885 Try to optimize FrmEntryMeta::get_ids_query
  classes/models/FrmEntryMeta.php
  tests/phpunit/entries/test_FrmEntryMeta.php
Labels: action: needs qa, run analysis, run tests

#2087 Add isset check in `should_join_fields_table`
  classes/models/FrmEntryMeta.php
Labels: run analysis, run tests

#2089 Properly deprecate edd plugin updater code, remove FrmDeprecated class and old `page_route` example
  classes/controllers/FrmAppController.php
  deprecated/FrmDeprecated.php
  deprecated/FrmEDD_SL_Plugin_Updater.php
  phpstan.neon
Labels: run analysis, run tests

#2090 Remove several deprecated functions
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFormActionsHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/helpers/FrmStylesHelper.php
  classes/models/fields/FrmFieldType.php
Labels: clean up, run analysis, run tests

#2091 Move AJAX hooks into load_ajax_hooks function
  classes/controllers/FrmHooksController.php
Labels: run analysis, run tests

#2092 Remove deprecated files
  classes/views/frm-fields/back-end/dropdown-field.php
  classes/views/frm-forms/new-form-overlay.php
  classes/views/frm-forms/new-form-overlay/leave-email.php
  classes/views/frm-forms/new-form-overlay/renew-account.php
  classes/views/welcome/show.php
Labels: run analysis, run tests

#2093 Fix Twilio icon color inconsistency in global settings menu
  css/admin/addons-page.css
  images/icons.svg
Labels: run analysis, run tests

#2094 Check tab content exists before making visible
  js/formidable_admin.js
Labels: run analysis, run tests

#2095 Update readme for v6.16.1
  changelog.txt
  readme.txt
Labels: run analysis, run tests

#2096 Add additional readme tags
  readme.txt
Labels: run analysis, run tests

#2049 Usage tracking v2
  classes/controllers/FrmAppController.php
  classes/controllers/FrmHooksController.php
  classes/controllers/FrmUsageController.php
  classes/models/FrmUsage.php
  js/admin/usage-tracking.js
  stubs.php
Labels: run analysis, deploy, run tests

#2097 Re-apply PR 2005
  changelog.txt
  classes/models/FrmFieldFormHtml.php
  readme.txt
Labels: run analysis, run tests

#2085 Fix submit button auto order change
  changelog.txt
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmSubmitHelper.php
  classes/models/FrmForm.php
  readme.txt
Labels: run analysis, run tests

#2098 Add stripe PR 378
  stripe/controllers/FrmStrpLiteEventsController.php
Labels: run analysis, run tests

#2099 Fix changelog grammar
  changelog.txt
  readme.txt
Labels: run analysis, run tests

#2100 Update styles accordions based on WP 6.7 changes
  classes/controllers/FrmStylesController.php
  classes/helpers/FrmAppHelper.php
  css/admin/style.css
  js/admin/style.js
  phpcs.xml
Labels: run analysis, run tests

#2101 Temporarily remove input shortcodes when rendering forms fix
  classes/views/frm-entries/form.php
Labels: run analysis, run tests

#2102 Prepare for 6.16.1
  changelog.txt
  classes/controllers/FrmUsageController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/models/FrmEntryMeta.php
  classes/models/FrmUsage.php
  deprecated/FrmEDD_SL_Plugin_Updater.php
  formidable.php
  languages/formidable.pot
  readme.txt
Labels: run analysis, run tests

#2103 Update tested to version
  readme.txt
Labels: run analysis, run tests

#2105 Prepare for v6.16.1.2
  changelog.txt
  readme.txt
Labels: run analysis, run tests

#2107 Add required addons to application modal
  classes/models/FrmApplicationTemplate.php
  css/admin/applications.css
  js/admin/applications.js
Labels: run analysis, run tests

#2109 Stop using jQuery for required field validation
  js/formidable.js
Labels: run analysis, run tests

#2110 Add some JS doc type comments
  js/formidable.js
Labels: run analysis, run tests

#2111 Add truncate option to FrmFieldValueSelector
  classes/models/FrmFieldValueSelector.php
Labels: run analysis, run tests

#2112 Make frm_after_delete_field hook safer
  js/formidable_admin.js
Labels: run analysis, run tests

#2113 Remove some redundant code
  classes/controllers/FrmFieldsController.php
Labels: run analysis, run tests

#2119 Improve bulk form trash
  classes/controllers/FrmFormsController.php
  classes/models/FrmForm.php
Labels: run analysis, run tests

#2120 Remove notices from other plugins on applications pages
  classes/controllers/FrmAppController.php
Labels: run analysis, run tests

#2121 Pro issue 5296 / stop decoding default values for non-array types
  classes/models/FrmField.php
  classes/models/fields/FrmFieldType.php
Labels: run analysis, run tests

#2122 Maybe delay error field focus
  js/formidable.js
Labels: run analysis, run tests

#2114 Add new action frm_dropdown_field_after_no_placeholder_option
  classes/views/frm-fields/front-end/dropdown-field.php
  package-lock.json
  package.json
Labels: run analysis, run tests

#2123 Allow arrays for radio type
  classes/models/fields/FrmFieldRadio.php
Labels: run analysis, run tests

#2125 Update readme for 6.16.2
  changelog.txt
  readme.txt
Labels: run analysis, run tests

#2126 Pro issue 5484
  classes/helpers/FrmFieldsHelper.php
Labels: run analysis, run tests

#2127 Prepare for v6.16.2
  changelog.txt
  classes/helpers/FrmAppHelper.php
  classes/models/FrmFieldValueSelector.php
  classes/models/fields/FrmFieldType.php
  classes/views/frm-fields/front-end/dropdown-field.php
  formidable.php
  js/formidable.min.js
  languages/formidable.pot
  readme.txt
  stripe/js/frmstrp.min.js
Labels: run analysis, run tests

#2128 Remove old deprecated css
  css/_single_theme.css.php
  css/custom_theme.css.php
Labels: run analysis, run tests

#2129 Remove unused variable frm_settings from CSS php file
  css/_single_theme.css.php
Labels: run analysis, run tests

#2131 Allow word breaking on dashboard entries table
  css/admin/dashboard.css
Labels: run analysis, run tests

#2132 Add free not first 30 inbox target
  classes/models/FrmInbox.php
Labels: run analysis, run tests

#2134 Drop more old vendor CSS
  css/font_icons.css
  css/frm_admin.css
Labels: run analysis, run tests

#2135 Strip unexpected characters from CSS output var names
  classes/helpers/FrmStylesHelper.php
Labels: run analysis, run tests

#2118 Pro issue 5418 / Use WordPress date and time settings for entry timestamp in edit/view entry sidebar
  classes/helpers/FrmAppHelper.php
  classes/views/frm-entries/_sidebar-shared-pub.php
  tests/cypress/e2e/Entries/EntriesPageDataValidations.cy.js
Labels: action: needs qa, run analysis, run tests

#2136 Drop unused deprecated CSS var
  css/frm_admin.css
Labels: run analysis, run tests

#2137 Remove CSS for frm_right_addon
  css/frm_admin.css
Labels: run analysis, run tests

#2138 Drop reference to unused CSS class pro feature
  css/frm_admin.css
Labels: run analysis, run tests

#2140 Deprecate more code
  classes/controllers/FrmAppController.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmHooksController.php
  classes/views/frm-forms/add_form_style_options.php
Labels: run analysis, run tests

#2036 Set aria-invalid to true only on name part input with error
  classes/controllers/FrmFieldsController.php
  classes/models/FrmFieldFormHtml.php
  classes/models/fields/FrmFieldCombo.php
  classes/models/fields/FrmFieldType.php
  css/_single_theme.css.php
  js/formidable.js
Labels: run analysis, deploy, run tests

#2141 Fix fatal error when field options is a string fix
  classes/helpers/FrmFieldsHelper.php
Labels: run analysis, run tests

#2144 Load lang on init hook
  classes/controllers/FrmHooksController.php
  tests/phpunit/misc/test_FrmMisc.php
Labels: run analysis, run tests

#2145 Improve support for null when preparing esc value
  classes/models/fields/FrmFieldType.php
Labels: run analysis, run tests

#2147 Add another index to entry items table
  classes/helpers/FrmAppHelper.php
  classes/models/FrmMigrate.php
Labels: run analysis, run tests

#2133 New duplicate check
  classes/models/FrmEntry.php
  classes/models/FrmEntryMeta.php
  js/formidable.js
Labels: action: needs qa, run analysis, run tests

#2148 Also add timestamp to unique id to further reduce risk of false posit…
  js/formidable.js
Labels: run analysis, run tests

#2143 Unschedule send usage event if it is disabled
  classes/controllers/FrmUsageController.php
  classes/models/FrmUsage.php
Labels: run analysis, run tests

#2149 Memoize unique match result and stop adding meta for repeater entries
  classes/models/FrmEntry.php
  classes/models/FrmEntryMeta.php
Labels: run analysis, run tests
