Repository Strategy11/formidable-forms, pull requests merged in 2024-04, with the labels that each got.

#1493 Move Submit and Rootline to builder
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmHooksController.php
  classes/factories/FrmFieldFactory.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmSubmitHelper.php
  classes/models/FrmField.php
  classes/models/fields/FrmFieldSubmit.php
  classes/models/fields/FrmFieldType.php
  classes/views/frm-entries/form.php
  classes/views/frm-fields/back-end/field-submit.php
  classes/views/frm-forms/add_field.php
  classes/views/frm-forms/add_field_links.php
  classes/views/frm-forms/form.php
  classes/views/frm-forms/settings-buttons.php
  css/frm_admin.css
  js/formidable_admin.js
  tests/fields/test_FrmSubmitHelper.php
  tests/forms/test_FrmFormsController.php
  tests/forms/test_FrmFormsControllerAjax.php
Labels: action: needs qa, run analysis, deploy

#1597 Add new filter for validation messages
  classes/controllers/FrmFieldsController.php
  tests/fields/test_FrmFieldsController.php
Labels: run analysis

#1604 Update sorting indicators
  classes/controllers/FrmDashboardController.php
  classes/controllers/FrmEntriesController.php
  classes/helpers/FrmListHelper.php
  deprecated/FrmWelcomeController.php
Labels: action: needs qa, run analysis

#1613 Add more type comments
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmAppHelper.php
  classes/models/FrmDb.php
  classes/models/FrmEntry.php
  classes/models/FrmEntryMeta.php
  classes/models/FrmField.php
  classes/models/FrmForm.php
Labels: run analysis

#1590 Enhanced Formatting Options for Phone Field
  classes/controllers/FrmFieldsController.php
  classes/models/fields/FrmFieldPhone.php
  classes/views/frm-fields/back-end/phone/phone-type.php
  classes/views/frm-fields/back-end/value-format.php
  css/frm_admin.css
  js/formidable_admin.js
Labels: action: needs qa, run analysis, deploy

#1628 Include Field ID in clean field filter
  classes/models/FrmField.php
Labels: run analysis

#1629 Prepare for 6.9
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmOnboardingWizardController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmOnboardingWizardHelper.php
  classes/helpers/FrmSubmitHelper.php
  classes/models/FrmField.php
  classes/models/FrmInstallPlugin.php
  classes/models/FrmSettings.php
  classes/models/fields/FrmFieldPhone.php
  classes/models/fields/FrmFieldSubmit.php
  classes/models/fields/FrmFieldType.php
  classes/views/frm-fields/back-end/field-submit.php
  classes/views/frm-fields/back-end/phone/phone-type.php
  classes/views/frm-forms/form.php
  formidable.php
  js/formidable.js
  js/formidable.min.js
  js/formidable_admin.js
  languages/formidable.pot
Labels: run analysis

#1630 Workflow performance improvements
  .github/workflows/phpcs.yml
  .github/workflows/phpstan.yml
  .github/workflows/syntax.yml
Labels: run analysis

#1632 Add strict phpstan rules
  classes/helpers/FrmEntriesListHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/models/FrmEmailStats.php
  classes/models/FrmEmailSummary.php
  classes/models/FrmFormApi.php
  classes/models/FrmFormTemplateApi.php
  classes/models/FrmSolution.php
  classes/models/FrmValidate.php
  classes/models/fields/FrmFieldDefault.php
  classes/models/fields/FrmFieldUserID.php
  classes/views/frm-fields/front-end/dropdown-field.php
  classes/views/shared/images-dropdown.php
  composer.json
  phpstan.neon
  tests/applications/test_FrmApplicationApi.php
  tests/applications/test_FrmApplicationsController.php
  tests/styles/test_FrmStyleApi.php
Labels: run analysis

#1633 Stop running unit test for every commit
  .github/workflows/phpunit.yml
Labels: run tests

#1634 Run some php cs fixer fixes
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmAppController.php
  classes/controllers/FrmDashboardController.php
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormTemplatesController.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmOverlayController.php
  classes/controllers/FrmStylesController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmCSVExportHelper.php
  classes/helpers/FrmDashboardHelper.php
  classes/helpers/FrmEntriesHelper.php
  classes/helpers/FrmFieldGridHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/helpers/FrmListHelper.php
  classes/helpers/FrmStylesCardHelper.php
  classes/helpers/FrmStylesPreviewHelper.php
  classes/helpers/FrmXMLHelper.php
  classes/models/FrmApplicationApi.php
  classes/models/FrmApplicationTemplate.php
  classes/models/FrmEmail.php
  classes/models/FrmEntry.php
  classes/models/FrmEntryValidate.php
  classes/models/FrmField.php
  classes/models/FrmForm.php
  classes/models/FrmFormAction.php
  classes/models/FrmFormApi.php
  classes/models/FrmFormState.php
  classes/models/FrmFormTemplateApi.php
  classes/models/FrmHoneypot.php
  classes/models/FrmStyleApi.php
  classes/models/FrmTableHTMLGenerator.php
  classes/models/FrmValidate.php
  classes/models/fields/FrmFieldCombo.php
  classes/models/fields/FrmFieldType.php
  classes/views/form-templates/template.php
  classes/views/summary-emails/stats.php
  deprecated/FrmDeprecated.php
  stripe/helpers/FrmTransLiteListHelper.php
  stubs.php
  tests/base/FrmUnitTest.php
  tests/emails/test_FrmEmail.php
  tests/forms/test_FrmFormsHelper.php
  tests/test_wordpress_plugin_tests.php
Labels: run analysis, run tests

#1636 Apply more phpcs fixer changes
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/models/FrmEmail.php
  classes/models/FrmEntryMeta.php
  classes/models/FrmField.php
Labels: run tests

#1637 Fix PHP CS Fixer rule: no_superfluous_elseif
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/helpers/FrmXMLHelper.php
Labels: run analysis, run tests

#1631 Exit early if call to mb_function fails
  classes/helpers/FrmAppHelper.php
Labels: run analysis, run tests

#1641 Php cs fixer
  .gitattributes
  .github/workflows/php-cs-fixer.yml
  .gitignore
  .php-cs-fixer.php
  bin/zip-plugin.sh
  classes/models/fields/FrmFieldCaptcha.php
  composer.json
  tests/misc/test_FrmDirectFileAccess.php
Labels: run analysis, run tests

#1642 Fix truncate on int
  classes/helpers/FrmAppHelper.php
Labels: run analysis, run tests

#1644 Php cs fixer phpdoc types order
  .php-cs-fixer.php
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmDashboardController.php
  classes/controllers/FrmEntriesAJAXSubmitController.php
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmSMTPController.php
  classes/controllers/FrmSettingsController.php
  classes/controllers/FrmStylesController.php
  classes/factories/FrmFieldFactory.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmCSVExportHelper.php
  classes/helpers/FrmDashboardHelper.php
  classes/helpers/FrmEmailSummaryHelper.php
  classes/helpers/FrmEntriesHelper.php
  classes/helpers/FrmEntriesListHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/helpers/FrmListHelper.php
  classes/helpers/FrmOnSubmitHelper.php
  classes/helpers/FrmStylesCardHelper.php
  classes/helpers/FrmStylesHelper.php
  classes/helpers/FrmStylesPreviewHelper.php
  classes/helpers/FrmSubmitHelper.php
  classes/models/FrmDb.php
  classes/models/FrmEmailStats.php
  classes/models/FrmEmailSummary.php
  classes/models/FrmEntry.php
  classes/models/FrmEntryFormatter.php
  classes/models/FrmEntryMeta.php
  classes/models/FrmEntryValidate.php
  classes/models/FrmField.php
  classes/models/FrmFieldFormHtml.php
  classes/models/FrmFieldOption.php
  classes/models/FrmForm.php
  classes/models/FrmFormAction.php
  classes/models/FrmFormMigrator.php
  classes/models/FrmInbox.php
  classes/models/FrmInstallerSkin.php
  classes/models/FrmSettings.php
  classes/models/FrmStyle.php
  classes/models/fields/FrmFieldNumber.php
  classes/models/fields/FrmFieldType.php
  stripe/controllers/FrmStrpLiteActionsController.php
  stripe/controllers/FrmStrpLiteLinkController.php
  stripe/controllers/FrmTransLiteActionsController.php
  stripe/controllers/FrmTransLiteCRUDController.php
  stripe/controllers/FrmTransLiteSubscriptionsController.php
  stripe/helpers/FrmStrpLiteConnectApiAdapter.php
  stripe/helpers/FrmStrpLiteConnectHelper.php
  stripe/helpers/FrmStrpLiteLinkRedirectHelper.php
  stripe/helpers/FrmStrpLiteSubscriptionHelper.php
  stripe/helpers/FrmStrpLiteUrlParamHelper.php
  stripe/helpers/FrmTransLiteAppHelper.php
  stripe/models/FrmStrpLiteAuth.php
  stripe/models/FrmTransLiteDb.php
  stubs.php
  tests/forms/test_FrmForm.php
Labels: run analysis, run tests

#1649 Drop more deprecated code
  deprecated/FrmDbDeprecated.php
  deprecated/FrmPointers.php
  formidable.php
Labels: run analysis, run tests

#1650 PHP CodeSniffer / Start checking for cognitive complexity
  phpcs.xml
Labels: run analysis, run tests

#1652 Add WP VIP Standard
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/helpers/FrmFormsListHelper.php
  classes/helpers/FrmListHelper.php
  classes/models/FrmField.php
  classes/models/FrmFieldValueSelector.php
  classes/models/fields/FrmFieldUrl.php
  classes/views/dashboard/templates/counters.php
  classes/views/form-templates/modals/leave-email-modal.php
  classes/views/form-templates/modals/name-your-form-modal.php
  classes/views/frm-fields/back-end/settings.php
  classes/views/frm-forms/add_field_links.php
  classes/views/frm-forms/error-modal.php
  classes/views/onboarding-wizard/index.php
  classes/views/onboarding-wizard/steps/default-email-address-step.php
  classes/views/onboarding-wizard/steps/license-management-step.php
  classes/views/shared/add-button.php
  classes/views/shared/admin-header.php
  classes/views/shared/reports-info.php
  classes/views/styles/_field-sizes.php
  classes/views/styles/_manage-styles-row.php
  phpcs.xml
  stripe/controllers/FrmStrpLitePaymentsController.php
Labels: run analysis, run tests

#1653 Remove useless isset
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmEntriesController.php
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmXMLController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmListHelper.php
  classes/helpers/FrmXMLHelper.php
  classes/models/FrmAddon.php
  classes/models/FrmEntry.php
  classes/models/FrmEntryValidate.php
  classes/models/FrmEntryValues.php
  classes/models/FrmForm.php
  classes/models/FrmFormAction.php
  classes/models/FrmFormMigrator.php
  classes/models/FrmMigrate.php
  classes/models/FrmSettings.php
  classes/views/addons/list.php
  classes/views/frm-entries/errors.php
  classes/views/shared/mb_adv_info.php
Labels: run analysis, run tests

#1654 Optimize the serialized string parser
  classes/helpers/FrmSerializedStringParserHelper.php
  classes/helpers/FrmStringReaderHelper.php
  classes/views/frm-form-actions/settings.php
  classes/views/frm-forms/settings-advanced.php
Labels: run analysis, run tests

#1655 Add isset check for inbox slidein
  classes/models/FrmInbox.php
Labels: run tests

#1657 Make some tiny optimizations
  classes/controllers/FrmFieldsController.php
  classes/helpers/FrmFieldsHelper.php
  classes/models/FrmField.php
  classes/views/frm-forms/add_field.php
Labels: run analysis, run tests

#1658 Clean up more
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmFormsHelper.php
  classes/models/FrmField.php
  classes/views/shared/mb_adv_info.php
Labels: run analysis, run tests

#1659 Add some type comments, make some checks more strict, remove an old v…
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmFieldsHelper.php
Labels: run analysis, run tests

#1660 Drop some old deprecated functions
  classes/helpers/FrmAppHelper.php
  deprecated/FrmDeprecated.php
Labels: run analysis, run tests

#1661 Store and re-use field selection data
  classes/controllers/FrmFieldsController.php
  classes/models/FrmFieldSelectionData.php
Labels: run analysis, run tests

#1662 Store and reuse type options for field type
  classes/controllers/FrmFieldsController.php
  classes/helpers/FrmFieldsHelper.php
  classes/models/FrmFieldTypeOptionData.php
Labels: run analysis, run tests

#1663 Use strict equals more
  classes/controllers/FrmEntriesController.php
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmSettingsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmEntriesHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/helpers/FrmXMLHelper.php
  classes/models/FrmEntryFormatter.php
  classes/models/FrmEntryShortcodeFormatter.php
  classes/models/FrmEntryValidate.php
  classes/models/FrmField.php
  classes/models/FrmFieldFormHtml.php
  classes/models/FrmForm.php
  classes/models/FrmFormAction.php
  classes/models/FrmStyle.php
  classes/models/FrmTableHTMLGenerator.php
  classes/models/fields/FrmFieldUrl.php
  classes/models/fields/FrmFieldUserID.php
  classes/views/addons/settings.php
  classes/views/frm-fields/back-end/field-choices.php
  classes/views/frm-fields/back-end/field-multiple.php
  classes/views/frm-fields/front-end/checkbox-field.php
  classes/views/frm-fields/front-end/radio-field.php
  deprecated/FrmDeprecated.php
  tests/base/FrmUnitTest.php
  tests/entries/test_FrmShowEntryShortcode.php
  tests/misc/test_FrmAppController.php
Labels: run analysis, run tests

#1664 Use strict not equals more, and drop some deprecated functions
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmStylesController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmEntriesHelper.php
  classes/models/FrmEntry.php
  classes/models/FrmEntryValidate.php
  deprecated/FrmDeprecated.php
Labels: run analysis, run tests

#1666 Stop hiding deprecated messages in phpcs config
  phpcs.xml
Labels: run analysis, run tests

#1667 Rector clean up
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmDashboardController.php
  classes/controllers/FrmEntriesController.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmStylesController.php
  classes/controllers/FrmXMLController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmCSVExportHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmXMLHelper.php
  classes/models/FrmAntiSpam.php
  classes/models/FrmForm.php
  classes/models/FrmStyle.php
  classes/views/frm-fields/back-end/field-multiple.php
  classes/views/frm-fields/input.php
  classes/views/frm-form-actions/settings.php
  classes/views/frm-forms/add_field_links.php
  classes/views/summary-emails/stats-plain.php
  classes/views/summary-emails/stats.php
  composer.json
  stripe/controllers/FrmStrpLiteSettingsController.php
  stripe/controllers/FrmTransLiteActionsController.php
  stripe/helpers/FrmStrpLiteAppHelper.php
  stripe/helpers/FrmStrpLiteConnectHelper.php
Labels: run analysis, run tests

#1668 More rector fixes
  classes/controllers/FrmXMLController.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmFormsListHelper.php
  classes/helpers/FrmListHelper.php
  classes/models/FrmEntry.php
  classes/models/FrmEntryFormatter.php
  classes/models/FrmEntryShortcodeFormatter.php
  classes/models/FrmEntryValues.php
  classes/models/FrmFieldValue.php
  classes/models/FrmFieldValueSelector.php
  classes/models/FrmFormMigrator.php
  classes/models/FrmStyle.php
  classes/models/fields/FrmFieldType.php
  classes/views/frm-fields/back-end/settings.php
  classes/views/frm-forms/settings-advanced.php
  classes/views/summary-emails/stats-plain.php
  stripe/helpers/FrmStrpLiteConnectHelper.php
  stripe/views/subscriptions/show.php
Labels: run analysis, run tests

#1669 Add a line limit phpcs rule
  phpcs.xml
Labels: run analysis, run tests

#1672 Add some type comments and strict checks
  classes/controllers/FrmStylesController.php
Labels: run analysis, run tests

#1673 Remove some old IE polyfills
  js/formidable.js
Labels: run analysis, run tests

#1674 Enforce order of since comment tag
  .php-cs-fixer.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmStylesController.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/helpers/FrmStylesHelper.php
  classes/models/FrmDb.php
  classes/models/FrmEntry.php
  classes/models/FrmForm.php
  classes/models/FrmPluginSearch.php
  classes/models/FrmTableHTMLGenerator.php
Labels: run analysis, run tests

#1675 Fix pro issue 5003 / Add deprecated messages for the use HTML5 setting
  classes/controllers/FrmAppController.php
  classes/views/frm-settings/misc.php
Labels: run analysis, run tests

#1676 Remove phpstan exceptions
  phpstan.neon
Labels: run analysis

#1678 More strict checks
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormActionsController.php
  classes/helpers/FrmEntriesListHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/models/FrmDb.php
  classes/models/FrmForm.php
  classes/views/frm-fields/back-end/settings.php
  tests/entries/test_FrmShowEntryShortcode.php
  tests/forms/test_FrmFormActionsController.php
  tests/misc/test_FrmAppHelper.php
Labels: run analysis, run tests

#1681 Remove more useless isset checks
  classes/models/FrmEntry.php
  classes/views/frm-entries/form.php
Labels: run analysis, run tests

#1682 Fix sonar issues
  classes/models/FrmEntry.php
  js/admin/dom.js
  js/formidable_admin.js
  stripe/js/frmstrp.js
Labels: run analysis, run tests

#1684 More sonar clean up and ignore more files
  .gitignore
  bin/zip-plugin.sh
  classes/models/FrmAddon.php
  classes/models/FrmEntry.php
Labels: run analysis, run tests

#1685 Use args[form] instead of getOne
  classes/models/fields/FrmFieldSubmit.php
Labels: run analysis, run tests

#1690 Add new file length limit Slevomat code standard rule
  classes/views/frm-forms/preview/footer.php
  classes/views/frm-forms/preview/header.php
  phpcs.xml
Labels: run analysis, run tests

#1610 Make dashboard videos show conditionally, add js required for the new global setting
  classes/controllers/FrmDashboardController.php
  classes/views/dashboard/dashboard.php
Labels: run analysis, run tests

#1692 Add missing static method stubs and drop some old deprecated functions
  classes/controllers/FrmEntriesController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/models/FrmApplicationTemplate.php
  classes/views/xml/posts_xml.php
  deprecated/FrmDeprecated.php
  phpstan.neon
  psalm.xml
  stripe/models/FrmTransLiteSubscription.php
  stubs.php
Labels: run analysis, run tests

#1693 Fix some phpstan contravariance issues
  classes/models/fields/FrmFieldType.php
  classes/models/fields/FrmFieldUserID.php
  phpstan.neon
Labels: run analysis, run tests

#1694 Add more type comments
  classes/models/FrmField.php
  classes/models/fields/FrmFieldType.php
Labels: run analysis, run tests
