Repository Strategy11/formidable-forms, pull requests merged in 2024-08, with the labels that each got.

#1896 Add array check to input shortcode sanitize fix
  classes/models/FrmField.php
Labels: run tests

#1537 Add filter for limiting repeater entries in list page
  classes/helpers/FrmEntriesHelper.php
  stubs.php
Labels: run analysis, run tests

#1893 search valid and invalid form title
  tests/cypress/e2e/Forms/searchFunctionality.cy.js
Labels: run analysis, run tests

#1897 Drop references to old html 5 setting
  classes/controllers/FrmAppController.php
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmStylesController.php
  classes/models/fields/FrmFieldNumber.php
  classes/models/fields/FrmFieldPhone.php
  classes/models/fields/FrmFieldType.php
  classes/views/frm-entries/new.php
  classes/views/frm-settings/misc.php
  js/formidable.js
Labels: run analysis, run tests

#1898 Improve frm_button_submit class check in `FrmFormsHelper::get_custom_submit` function
  classes/helpers/FrmFormsHelper.php
Labels: run analysis, run tests

#1894 Do not add a new option to conditional logic if renaming an option
  js/formidable_admin.js
Labels: run analysis, run tests

#1901 Stop using jit/opcache in phpstan workflow
  .github/workflows/phpstan.yml
Labels: run analysis, run tests

#1895 Prevent user id field from being dragged into field group
  js/formidable_admin.js
Labels: run analysis, run tests

#1903 Exclude submit field from entry table
  classes/models/FrmEntryFormatter.php
Labels: run tests

#1601 Make conditional logic dropdown options label/value update with field options
  js/formidable_admin.js
Labels: run analysis, run tests

#1905 Fix undefined function: groupIncludesBreakOrHidden
  js/formidable_admin.js
Labels: run tests

#1899 Add label to entries list checkboxes
  classes/helpers/FrmEntriesListHelper.php
  classes/helpers/FrmFormsListHelper.php
  tests/cypress/e2e/admin-a11y.cy.js
Labels: run analysis, run tests

#1904 Check if openssl_encrypt function is defined before attempt to call it
  classes/models/FrmFormState.php
Labels: run analysis, run tests

#1900 validate data in list and excerpt view in forms page
  tests/cypress/e2e/Forms/formPageDataValidation.cy.js
  tests/cypress/support/commands.js
Labels: run analysis, run tests

#1909 Use less jQuery to scroll to first field
  js/formidable.js
Labels: run analysis, run tests

#1910 Stop using jQuery `.prepend` function
  js/formidable.js
Labels: run analysis, run tests

#1911 Move frmtoggle logic from front end scripts to admin entries JS
  js/formidable.js
  js/formidable_admin.js
Labels: run analysis, run tests

#1912 Stop using jQuery hasClass to check if JS validation is enabled
  js/formidable.js
Labels: run analysis, run tests

#1913 Drop resend email JS
  classes/helpers/FrmAppHelper.php
  js/formidable.js
Labels: run analysis, run tests

#1914 Remove error classes from field using vanilla JS
  js/formidable.js
Labels: run analysis, run tests

#1915 Simplify views checks
  classes/controllers/FrmAppController.php
  classes/controllers/FrmEntriesController.php
Labels: run analysis, run tests

#1916 Remove more deprecated code
  classes/controllers/FrmAppController.php
Labels: run analysis, run tests

#1907 Stop using font icons for form actions collapsible
  classes/views/frm-form-actions/form_action.php
  css/frm_admin.css
Labels: run analysis, run tests

#1921 Fix issue with duplicate turnstile renders
  classes/models/fields/FrmFieldCaptcha.php
Labels: run analysis, run tests

#1917 validate elements and data of entries of submitted forms
  tests/cypress/e2e/Entries/EntriesPageDataValidations.cy.js
  tests/cypress/e2e/Entries/doNotStoreEntries.cy.js
Labels: run analysis, run tests

#1332 Only unserialize or decode entry meta for expected types
  classes/helpers/FrmFieldsHelper.php
  classes/models/FrmEntryMeta.php
Labels: run analysis, run tests

#1927 Pro issue 5200 / Stop logging overdue cron count as an error
  stripe/controllers/FrmTransLiteAppController.php
  stripe/models/FrmTransLiteLog.php
Labels: run analysis, run tests

#1922 Hide notice from some plugins
  css/frm_admin.css
Labels: run analysis, run tests

#1924 Use SVG for tooltip icon
  classes/helpers/FrmAppHelper.php
  classes/views/frm-forms/settings-advanced.php
  classes/views/frm-forms/spam-settings/antispam.php
  classes/views/frm-forms/spam-settings/honeypot.php
  classes/views/frm-settings/captcha/captcha.php
  classes/views/frm-settings/general.php
  classes/views/frm-settings/messages.php
  classes/views/styles/_buttons.php
  classes/views/styles/_field-sizes.php
  css/frm_admin.css
  js/formidable_admin.js
  stripe/helpers/FrmTransLiteListHelper.php
  stripe/views/settings/messages.php
Labels: run analysis, run tests

#1930 Make hasClass function safer
  js/formidable.js
Labels: run analysis, run tests

#1931 Deprecate unused view
  stripe/views/payments/entry_sidebar.php
Labels: run analysis, run tests

#1929 Use FrmAppHelper::mb_function to use mb_strlen when it is available
  classes/models/fields/FrmFieldText.php
Labels: run analysis, run tests

#1932 Fix js validate check
  js/formidable.js
Labels: run analysis, run tests

#1926 Start working on readme for version 6.12
  changelog.txt
  readme.txt
Labels: run analysis, run tests

#1933 Prepare for 6.12
  changelog.txt
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmEntriesListHelper.php
  classes/models/FrmFormState.php
  formidable.php
  js/formidable.min.js
  languages/formidable.pot
  readme.txt
  stripe/models/FrmTransLiteLog.php
  stripe/views/payments/entry_sidebar.php
Labels: run analysis, run tests

#1936 Fix issue when scrolling to first field when handling stripe error
  js/formidable.js
Labels: run analysis, run tests

#1937 Update readme for version 6.12.1
  changelog.txt
  readme.txt
Labels: run tests

#1938 Fix: Improve compatibility with old versions of Lite when checking for Chosen
  classes/helpers/FrmStylesHelper.php
  css/_single_theme.css.php
  css/custom_theme.css.php
Labels: run analysis, run tests

#1939 Prepare for 6.12.1
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmStylesHelper.php
  formidable.php
  js/formidable.min.js
  languages/formidable.pot
Labels: run analysis, run tests

#1940 Prepare for 6.13
  changelog.txt
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmStylesHelper.php
  formidable.php
  languages/formidable.pot
  readme.txt
Labels: run analysis, run tests

#1934 delete forms permanently
  tests/cypress/e2e/Forms/bulkDeleteForms.cy.js
  tests/cypress/e2e/Forms/deleteForms.cy.js
  tests/cypress/e2e/Forms/formPageDataValidation.cy.js
  tests/cypress/support/commands.js
Labels: run analysis, run tests

#1906 Avoid corrupted custom html when duplicating field
  classes/helpers/FrmFieldsHelper.php
Labels: run analysis, run tests

#1942 Add type comments to front end js
  js/formidable.js
Labels: run analysis, run tests

#1918 Replace font icons with SVGs for edd license status
  classes/views/addons/settings.php
  css/frm_admin.css
  js/formidable_admin.js
Labels: run analysis, run tests

#1944 Fix pro issue 4956 / Add checks that add on variables are array with …
  classes/controllers/FrmSimpleBlocksController.php
Labels: run analysis, run tests

#1946 Fix JS error when trying to validate readonly time field
  js/formidable.js
Labels: run analysis, run tests

#1943 Make merge into row popup appear on top of section styling
  css/frm_admin.css
Labels: run tests

#1947 Drop payments page a11y test
  tests/cypress/e2e/admin-a11y.cy.js
Labels: run tests

#1467 improve order fields performance on heavy forms
  js/formidable_admin.js
Labels: action: needs qa, run analysis, run tests

#1928 Implement AJAX Submission Notification for Formidable Modal - Lite Version
  classes/controllers/FrmSimpleBlocksController.php
Labels: run analysis, run tests

#1949 Add some type coments
  classes/helpers/FrmFormsHelper.php
Labels: run analysis, run tests

#1950 Add type check before populating field options
  classes/helpers/FrmEntriesHelper.php
Labels: run analysis, run tests

#1951 Add frm_get_ajax_form_errors event
  js/formidable.js
Labels: run analysis, run tests

#1925 Sync conditional logic options after field option deletion
  js/formidable_admin.js
Labels: run analysis, deploy, run tests

#1955 Only add Cloudflare Turnstile captcha for visible elements
  js/formidable.js
Labels: run analysis, run tests
