Repository Strategy11/formidable-forms, pull requests merged in 2024-01, with the labels that each got.

#1433 Fix js Error when switching Product field type
  js/formidable_admin.js
Labels: action: needs qa

#1401 Avoid deprecation warnings when calling template functions
  classes/controllers/FrmFormsController.php
  classes/views/frm-forms/preview/footer.php
  classes/views/frm-forms/preview/header.php
Labels: action: needs tests

#1425 Stop requiring CC field if stripe intent is in request
  classes/controllers/FrmFormsController.php
  phpcs.xml
  stripe/controllers/FrmStrpLiteActionsController.php
  stripe/controllers/FrmStrpLiteHooksController.php
Labels: action: needs qa, run analysis

#1427 Use large icons in summary emails
  classes/helpers/FrmEmailSummaryHelper.php
  images/chart.png
  images/notice.png
  images/speaker.png
  images/trophy.png
Labels: deploy

#1436 Avoid a db error when getting payments stats
  stripe/models/FrmTransLitePayment.php
Labels: run analysis

#1438 Fix Layout for Email Settings: CC, BCC, and From Fields
  classes/views/frm-form-actions/_email_settings.php
  css/frm_admin.css
Labels: run analysis, deploy

#1439 Pro issue 4647
  classes/helpers/FrmAppHelper.php
  classes/models/FrmEntryFormatter.php
  classes/models/FrmEntryValidate.php
  classes/models/fields/FrmFieldType.php
  js/admin/dom.js
  js/formidable_admin.js
  tests/fields/test_FrmFieldType.php
Labels: run analysis

#1440 Update since versions, prepare for 6.7.1
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/models/FrmAddon.php
  classes/models/fields/FrmFieldType.php
  classes/views/frm-forms/create-template-from-an-existing-form.php
  classes/views/frm-forms/list-template.php
  classes/views/frm-forms/list-templates.php
  classes/views/frm-forms/new-form-overlay.php
  classes/views/frm-forms/new-form-overlay/code-from-email.php
  classes/views/frm-forms/new-form-overlay/leave-email.php
  classes/views/frm-forms/new-form-overlay/renew-account.php
  classes/views/frm-forms/new-form-overlay/upgrade-body.php
  formidable.php
  languages/formidable.pot
  stripe/controllers/FrmStrpLiteActionsController.php
Labels: run analysis

#1445 Fix issue with toggling styles for form
  changelog.txt
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFormsHelper.php
  formidable.php
  languages/formidable.pot
  phpstan.neon
  readme.txt
Labels: run analysis

#1448 Add tests for FrmFormsHelper::get_form_style
  classes/helpers/FrmFormsHelper.php
  tests/forms/test_FrmFormsHelper.php
Labels: run analysis

#1447 Fix styling toggle appears enabled when disabled from global settings
  classes/views/frm-forms/settings-buttons.php
  classes/views/styles/_styles-list.php
Labels: action: needs qa, run analysis

#1444 Merge css for tags
  classes/views/form-templates/modals/upgrade-modal.php
  css/admin/form-templates.css
  css/frm_admin.css
  js/form-templates.js
  js/form-templates.js.map
  js/formidable_admin.js
  js/formidable_blocks.js.map
  js/src/form-templates/elements/applicationTemplatesElement.js
Labels: action: needs qa

#1454 Fix for Blank "View Payment" Page
  css/frm_admin.css
Labels: action: needs qa, deploy

#1391 Add a filter that allows updating form ids for fields in Stripe action
  stripe/js/frmstrp.js
  stripe/models/FrmTransLiteAction.php
Labels: run analysis

#1450 Switch a few options to not autoload for performance
  classes/controllers/FrmAddonsController.php
  classes/models/FrmFormState.php
  classes/models/FrmSettings.php
Labels: action: needs qa

#1431 Implement Deactivate and Uninstall Buttons for Add-Ons on Formidable Add-Ons Page
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmAppController.php
  classes/controllers/FrmHooksController.php
  classes/helpers/FrmAppHelper.php
  css/frm_admin.css
  js/admin/addons.js
  js/formidable_admin.js
Labels: action: needs qa, run analysis

#1466 Resolve Overlapping Search Boxes Issue
  css/frm_admin.css
Labels: action: needs qa, deploy

#1468 Fix pro issue 4717 / Check svg has a use child when cleaning HTML
  js/admin/dom.js
Labels: action: needs qa

#1477 PHP fix (long if in styleshelper
  classes/helpers/FrmStylesHelper.php
Labels: run analysis

#1463 Fix: Hide 'Entries' for XML Export in Lite Mode (#4709)
  classes/views/xml/import_form.php
  css/frm_admin.css
Labels: priority: high, action: needs qa, deploy

#1455 Add Stripe PRs 315, 316, and 318
  stripe/controllers/FrmStrpLiteAppController.php
  stripe/controllers/FrmStrpLiteLinkController.php
  stripe/helpers/FrmStrpLiteConnectHelper.php
  stripe/helpers/FrmStrpLiteLinkRedirectHelper.php
  stripe/helpers/FrmStrpLiteSubscriptionHelper.php
  stripe/js/frmstrp.js
  stripe/models/FrmStrpLiteAuth.php
Labels: action: needs qa, run analysis

#1479 Add unit tests for color brightness and add support for hsl to hex
  classes/helpers/FrmStylesHelper.php
  tests/styles/test_FrmStylesHelper.php
Labels: run analysis

#1461 Fix: Correct Placement of Support Footer Links on Lite-Reports Page
  classes/views/shared/reports-info.php
  js/formidable_admin.js
Labels: priority: high, action: needs qa, deploy

#1462 Pro issue 4713 / Add a draft flag to new fields and hide them from the front end except for on preview
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmFieldsHelper.php
  classes/models/fields/FrmFieldType.php
  classes/views/frm-fields/back-end/settings.php
  classes/views/frm-forms/add_field_links.php
  classes/views/frm-forms/edit.php
  js/formidable_admin.js
  tests/fields/test_FrmFieldType.php
  tests/fields/test_FrmFieldsController.php
  tests/fields/test_FrmFieldsHelper.php
Labels: action: needs qa, run analysis

#1482 Stop triggering drop field functions multiple times
  js/formidable_admin.js
Labels: action: needs qa

#1441 Add in-plugin education for graph block
  classes/controllers/FrmSimpleBlocksController.php
  images/demo-graph.svg
  js/formidable_blocks.js
  js/src/blocks.js
  js/src/form/graph.js
Labels: run analysis

#1484 Resolve Display Issue of Install Add-On Buttons in Formidable Forms (Lite Version PR)
  js/formidable_admin.js
Labels: action: needs qa, run analysis

#1457 Summary email enhancement
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmEmailSummaryHelper.php
  classes/models/FrmEmailSummary.php
  classes/models/FrmEmailYearly.php
  classes/models/FrmMigrate.php
  classes/models/FrmSettings.php
  classes/views/summary-emails/base-plain.php
  classes/views/summary-emails/stats-plain.php
Labels: action: needs qa, run analysis

#1491 Fix pro issue 4724
  classes/controllers/FrmFormsController.php
Labels: run analysis

#1492 Prepare for 6.8
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmAppController.php
  classes/controllers/FrmApplicationsController.php
  classes/controllers/FrmDashboardController.php
  classes/controllers/FrmFormTemplatesController.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmInboxController.php
  classes/controllers/FrmSimpleBlocksController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmDashboardHelper.php
  classes/helpers/FrmEmailSummaryHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmStylesHelper.php
  classes/models/FrmEmailSummary.php
  classes/models/FrmEmailYearly.php
  classes/models/FrmEntry.php
  classes/models/FrmForm.php
  classes/models/FrmMigrate.php
  classes/models/fields/FrmFieldType.php
  classes/views/dashboard/templates/pro-features-list.php
  deprecated/FrmWelcomeController.php
  formidable.php
  languages/formidable.pot
  stripe/helpers/FrmStrpLiteSubscriptionHelper.php
  stripe/js/frmstrp.min.js
  stripe/models/FrmStrpLiteAuth.php
  stripe/models/FrmTransLiteAction.php
Labels: run analysis

#1485 Add label to form list checkboxes
  classes/helpers/FrmFormsListHelper.php
Labels: run analysis

#1486 Fix action limit message for actions with more than one limit
  classes/helpers/FrmAppHelper.php
  js/formidable_admin.js
Labels: run analysis
