Repository Strategy11/formidable-forms, pull requests merged in 2024-02, with the labels that each got.

#1497 New filter `frm_inbox_message_is_for_user`
  classes/models/FrmInbox.php
Labels: run analysis

#1508 Fix Pro issue 4753
  classes/controllers/FrmSettingsController.php
  js/formidable_admin.js
Labels: run analysis

#1512 Prepare for 6.8.2
  changelog.txt
  classes/helpers/FrmAppHelper.php
  formidable.php
  languages/formidable.pot
  readme.txt
  tests/misc/test_FrmFormApi.php
Labels: run analysis

#1513 Pro issue 4776 / Add support for a new value arg in show search box f…
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFormsHelper.php
Labels: run analysis

#1522 Add field name shortcode for error messages
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/models/FrmSettings.php
  classes/models/fields/FrmFieldType.php
  tests/fields/test_FrmFieldsHelper.php
Labels: action: needs qa, run analysis

#1529 Add an isset check to FrmFormApi::get_addon_for_license
  classes/models/FrmFormApi.php
Labels: run analysis

#1531 Fix deprecated messaged when running Stripe unit tests
  tests/base/FrmUnitTest.php
Labels: run analysis

#1535 Remove a lot of old CSS rules that are no longer required
  classes/controllers/FrmSMTPController.php
  classes/models/FrmSolution.php
  css/_single_theme.css.php
  css/custom_theme.css.php
  css/font_icons.css
  css/frm_admin.css
  css/frm_grids.css
Labels: run analysis

#1536 Make hex to rgb function work with rgb values
  classes/helpers/FrmStylesHelper.php
  css/_single_theme.css.php
  tests/styles/test_FrmStylesHelper.php
Labels: run analysis

#1532 Update connect flow
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmHooksController.php
  classes/helpers/FrmAppHelper.php
Labels: action: needs qa

#1505 Add Missing Animation to Field Group Message Element
  .github/workflows/qadeploy.yml
  classes/controllers/FrmAppController.php
  classes/controllers/FrmDashboardController.php
  classes/controllers/FrmFormTemplatesController.php
  classes/controllers/FrmOverlayController.php
  css/admin/animations.css
  js/form-templates.js
  js/form-templates.js.map
  js/formidable_dashboard.js
  js/formidable_dashboard.js.map
  js/formidable_overlay.js
  js/formidable_overlay.js.map
  js/src/common/utilities/animation.js
Labels: action: needs qa, run analysis, deploy

#1526 Fix Undefined Index 'name' in Form Templates Unit Test
  classes/helpers/FrmFormTemplatesHelper.php
Labels: run analysis

#1549 Separate value input is visible when disabled fix
  css/frm_admin.css
  tests/emails/test_FrmEmailSummaryHelper.php
Labels: run analysis
