Repository Strategy11/formidable-forms, pull requests merged in 2024-05, with the labels that each got.

#1695 Call pro intl phone validation function instead of checking regex pat…
  js/formidable.js
Labels: run analysis, run tests

#1697 Do not init inbox if there are no importable forms
  classes/helpers/FrmFormMigratorsHelper.php
Labels: run analysis, run tests

#1699 Fix pro issue 4975 / Use Cloudflare worker for add-ons endpoint when …
  classes/models/FrmFormApi.php
Labels: run analysis, run tests

#1700 Add npm commands for composer dev dependencies
  package.json
Labels: run analysis, run tests

#1703 Move to newer WordPress ESLint standard
  .eslintrc.json
  .github/workflows/cypress.yml
  js/formidable.js
  js/formidable_admin.js
  package-lock.json
  package.json
  stripe/js/frmstrp.js
Labels: run tests

#1704 Replace var with let/const in admin js files
  .eslintrc.json
  js/formidable.js
  js/formidable_admin.js
  js/formidable_admin_global.js
  tests/cypress/e2e/formidable-admin.cy.js
  tests/cypress/e2e/spec.cy.js
Labels: run tests

#1705 Improve e2e tests
  cypress.config.js
  tests/cypress/e2e/formidable-admin.cy.js
Labels: run tests

#1706 Clean up e2e test and add a few more
  tests/cypress/e2e/formidable-admin.cy.js
Labels: run tests

#1686 Feature/calendar views
  .github/workflows/cypress.yml
  classes/controllers/FrmSimpleBlocksController.php
  css/frm_blocks.css
  images/blocks/views-block-placeholder.jpg
  js/formidable_blocks.js
  js/formidable_blocks.js.map
  js/onboarding-wizard.js.map
  js/src/api/class-addon-api.js
  js/src/api/index.js
  js/src/blocks.js
  js/src/form/css/button.module.css
  js/src/form/views.js
  package-lock.json
  package.json
  webpack.config.js
Labels: run analysis, run tests

#1698 Avoid duplicate aria description IDs fix
  classes/models/fields/FrmFieldType.php
  tests/phpunit/fields/test_FrmFieldType.php
Labels: run analysis, run tests

#1713 The string "Global Settings" in FrmAppController.php is not displayed translated
  classes/controllers/FrmAppController.php
Labels: run analysis, run tests

#1709 Fix: [i18n] The strings in Style are not displayed translated
  classes/controllers/FrmStylesController.php
Labels: run analysis, run tests

#1707 Fix: [i18n] The strings in Applications are not displayed translated
  classes/controllers/FrmApplicationsController.php
Labels: run analysis, run tests

#1696 Update readme for v6.9.1
  changelog.txt
  readme.txt
Labels: run analysis, run tests

#1717 Add some missing type comments
  classes/controllers/FrmFormActionsController.php
  classes/helpers/FrmAppHelper.php
Labels: run analysis, run tests

#1718 Add some additional type comments
  classes/models/FrmDb.php
  classes/models/FrmFormAction.php
Labels: run analysis, run tests

#1719 Start testing a11y using cypress axe / improve import/export page accessibility
  classes/views/xml/import_form.php
  package-lock.json
  package.json
  tests/cypress/e2e/admin-a11y.cy.js
  tests/cypress/e2e/admin.cy.js
  tests/cypress/support/index.js
Labels: run analysis, run tests

#1720 Add sonar js eslint ruleset
  .eslintrc.json
  js/formidable.js
  js/formidable_admin.js
  package-lock.json
  package.json
Labels: run analysis, run tests

#1725 Use off for autocomplete on honeypot not false
  classes/models/FrmHoneypot.php
Labels: run analysis, run tests

#1726 Stop including the frmUpdateField function as a global function when …
  classes/helpers/FrmAppHelper.php
  js/formidable.js
Labels: run analysis, run tests

#1727 Drop more deprecated code
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmAppController.php
  classes/controllers/FrmEntriesController.php
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/helpers/FrmStylesHelper.php
  deprecated/FrmDeprecated.php
  deprecated/FrmWelcomeController.php
  formidable.php
Labels: run analysis, run tests

#1728 Drop support for IE11 and update var to `let`/`const` in `formidable.js`
  .eslintrc.json
  js/formidable.js
  js/formidable_admin.js
  package-lock.json
  package.json
Labels: run analysis, run tests

#1723 Use field keys for errors not ids
  js/formidable.js
Labels: run analysis, run tests

#1729 Drop several deprecated global JS functions and deprecate frmUpdateField
  js/formidable.js
Labels: run analysis, run tests

#1730 Get rid of more deprecated code
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmHooksController.php
  classes/controllers/FrmSettingsController.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmFormActionsHelper.php
  classes/helpers/FrmFormMigratorsHelper.php
  classes/models/FrmFormAction.php
  deprecated/FrmDeprecated.php
Labels: run analysis, run tests

#1731 Deprecate and conditionally include resend email logic
  classes/helpers/FrmAppHelper.php
  js/formidable.js
Labels: run analysis, run tests

#1732 Drop more IE specific code from Lite js
  js/formidable.js
Labels: run analysis, run tests

#1733 Update hasClass function to use a more modern classList.contains check
  js/formidable.js
Labels: run analysis, run tests

#1734 Simplify trigger custom event function
  js/formidable.js
Labels: run analysis, run tests

#1735 Store and reuse field selection data when outputting shortcode options optimization
  classes/helpers/FrmFormsHelper.php
Labels: run analysis, run tests

#1691 Use decimal for a single decimal place fix
  stripe/controllers/FrmTransLiteActionsController.php
  tests/phpunit/stripe/test_FrmTransLiteActionsController.php
Labels: run analysis, run tests

#1736 Map new address field ids on map view import
  classes/helpers/FrmXMLHelper.php
Labels: run analysis, run tests

#1738 Drop old css moz drop shadow rule
  css/custom_theme.css.php
Labels: run analysis, run tests

#1739 Stop using deprecated "alpha" in css
  css/frm_admin.css
Labels: run analysis, run tests

#1737 fix calendar view options on import
  classes/helpers/FrmXMLHelper.php
Labels: run analysis, run tests

#1740 Drop IE specific flexbox styles
  css/frm_blocks.css
Labels: run analysis, run tests

#1742 Add a null check to avoid deprecated message when previewing
  classes/controllers/FrmFormsController.php
Labels: run analysis, run tests

#1743 Add some comments to forms controller
  classes/controllers/FrmFormsController.php
Labels: run analysis, run tests

#1749 Post param cleanup
  classes/controllers/FrmDashboardController.php
  classes/controllers/FrmStylesController.php
  classes/helpers/FrmAppHelper.php
Labels: run analysis, run tests

#1750 Add more type comments
  classes/helpers/FrmAppHelper.php
Labels: run analysis, run tests

#1752 Update no fields border styling
  css/frm_admin.css
Labels: run analysis, run tests

#1747 Fix deprecated notice when calling trim
  classes/helpers/FrmAppHelper.php
Labels: run analysis, run tests

#1619 Necessary code for repeater actions
  classes/controllers/FrmFormActionsController.php
  classes/models/FrmEmail.php
  classes/models/FrmFormAction.php
  classes/views/frm-form-actions/_action_inside.php
Labels: run analysis, deploy, run tests

#1751 Pro issue 5074 / Print media templates to fix email actions media but…
  classes/controllers/FrmFormsController.php
Labels: action: needs qa, run analysis, run tests

#1755 Add a new action to support AI generated forms
  classes/views/form-templates/index.php
  css/admin/form-templates.css
  images/icons.svg
Labels: run analysis, run tests

#1758 Move summary_email_content_args filter to get_content_args()
  classes/models/FrmEmailSummary.php
Labels: run analysis, run tests

#1756 Fix issue with "All Templates" click resulting in no visible templates
  js/form-templates.js
  js/form-templates.js.map
  js/src/form-templates/events/categoryListener.js
Labels: action: needs qa, run analysis, deploy, run tests

#1759 Pro issue 5058 update form button settings
  classes/controllers/FrmFormsController.php
  classes/views/frm-forms/add_form_style_options.php
  classes/views/frm-forms/settings-buttons.php
Labels: run analysis, run tests

#1760 Do some small FrmAppHelper tweaks
  classes/helpers/FrmAppHelper.php
Labels: run analysis, run tests

#1761 Use strict equals more
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/models/FrmDb.php
  classes/models/FrmEntryFormatter.php
  classes/models/FrmEntryMeta.php
  classes/models/FrmField.php
  classes/models/FrmForm.php
  classes/models/FrmMigrate.php
  classes/views/addons/settings.php
  classes/views/styles/_sample_form.php
  stripe/controllers/FrmTransLiteActionsController.php
  tests/phpunit/emails/test_FrmEmail.php
  tests/phpunit/forms/test_FrmFormsController.php
Labels: run analysis, run tests

#1762 Store and reuse field selection data when displaying field type in options
  classes/models/fields/FrmFieldType.php
  css/font_icons.css
Labels: run analysis, run tests

#1757 create multiple forms and bulk delete them from form list page
  tests/cypress/e2e/Forms/bulkDeleteForms.cy.js
  tests/cypress/e2e/Forms/duplicateForm.cy.js
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
Labels: run analysis, run tests

#1688 Add function to check event data for error
  stripe/controllers/FrmTransLiteActionsController.php
  stripe/js/frmstrp.js
Labels: action: needs qa, run analysis, run tests

#1753 Start working on change log for v6.10
  .github/workflows/syntax.yml
  changelog.txt
  classes/helpers/FrmAppHelper.php
  readme.txt
Labels: run analysis, run tests

#1763 Prepare for v6.10
  classes/helpers/FrmAppHelper.php
  formidable.php
  js/formidable.min.js
  js/formidable_blocks.js
  js/formidable_dashboard.js
  js/formidable_overlay.js
  js/onboarding-wizard.js
  languages/formidable.pot
  stripe/js/frmstrp.min.js
Labels: run analysis, run tests

#1764 Update since versions
  classes/controllers/FrmFormActionsController.php
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/helpers/FrmStylesHelper.php
  classes/models/FrmFormAction.php
  classes/models/fields/FrmFieldType.php
  classes/views/form-templates/index.php
  classes/views/frm-form-actions/_action_inside.php
  js/formidable.js
  stripe/controllers/FrmTransLiteActionsController.php
  stripe/js/frmstrp.js
Labels: run analysis, run tests

#1765 Update minified frontend js
  js/formidable.min.js
Labels: run analysis, run tests

#1715 Add subscription limit setting and a feature to auto-cancel a subscription after it reaches the payment limit
  stripe/controllers/FrmStrpLiteEventsController.php
  stripe/helpers/FrmStrpLiteSubscriptionHelper.php
  stripe/helpers/FrmTransLiteAppHelper.php
  stripe/helpers/FrmTransLiteListHelper.php
  stripe/models/FrmTransLiteAction.php
  stripe/views/action-settings/payments-options.php
  tests/phpunit/bootstrap.php
  tests/phpunit/stripe/FrmStrpLiteUnitTest.php
Labels: run analysis, run tests

#1769 Stop loading dropzone css on form list page
  classes/controllers/FrmAppController.php
Labels: run analysis, run tests

#1770 Store and reuse tinymce formdiable button optimization
  classes/controllers/FrmFormsController.php
Labels: run analysis, run tests

#1772 Small tweaks/cleanup
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/views/frm-fields/back-end/settings.php
Labels: run analysis, run tests
