Repository Strategy11/formidable-forms, pull requests merged in 2024-07, with the labels that each got.

#1817 Replace nbsp from plain email content
  classes/models/FrmEmail.php
Labels: run tests

#1831 view and delete an entry
  tests/cypress/e2e/Entries/deleteEntries.cy.js
Labels: run analysis, run tests

#1835 Drop down arrow icon from insert form pop up
  classes/views/frm-forms/insert_form_popup.php
Labels: run tests

#1836 update success message after submitting form
  classes/models/FrmFieldValueSelector.php
  tests/cypress/e2e/GlobalSettings/globalSettingsUpdates.cy.js
Labels: run analysis, run tests

#1837 Use the right class name in comment fix
  classes/models/FrmFieldValueSelector.php
  stubs.php
Labels: run analysis, run tests

#1838 Update modal close icon color styling
  css/frm_admin.css
Labels: run analysis, run tests

#1830 Output screen reader texts on forms and entries list pages
  classes/helpers/FrmEntriesListHelper.php
  classes/helpers/FrmFormsListHelper.php
  classes/helpers/FrmListHelper.php
  stripe/helpers/FrmTransLiteListHelper.php
Labels: run analysis, run tests

#1840 Remove translations that are now officially translated in the WP.org …
  languages/formidable-it_IT.mo
  languages/formidable-it_IT.po
  languages/formidable-ja.mo
  languages/formidable-ja.po
Labels: run analysis, run tests

#1843 Fix typos
  bin/build-plugin.sh
  bin/git-release.sh
  changelog.txt
  classes/controllers/FrmDashboardController.php
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmHooksController.php
  classes/controllers/FrmOverlayController.php
  classes/controllers/FrmStylesController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmDashboardHelper.php
  classes/helpers/FrmEntriesHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/models/FrmAntiSpam.php
  classes/models/FrmDb.php
  classes/models/FrmFieldCaptchaSettings.php
  classes/models/FrmFormMigrator.php
  classes/models/FrmInbox.php
  classes/models/fields/FrmFieldCaptcha.php
  classes/models/fields/FrmFieldType.php
  classes/views/onboarding-wizard/steps/install-formidable-pro-step.php
  classes/views/styles/_styles-edit.php
  deprecated/FrmEDD_SL_Plugin_Updater.php
  js/formidable_admin.js
  readme.txt
  stripe/models/FrmStrpLiteAuth.php
  tests/cypress/e2e/admin-a11y.cy.js
  tests/cypress/e2e/form-preview-a11y.cy.js
  tests/phpunit/styles/test_FrmStylesHelper.php
Labels: run analysis, run tests

#1844 Fix more typos
  classes/controllers/FrmFormsController.php
  classes/models/FrmField.php
  classes/models/FrmMigrate.php
  tests/cypress/e2e/Forms/formsSettings.cy.js
  tests/phpunit/emails/test_FrmEmailSummaryHelper.php
Labels: run analysis, run tests

#1845 Define typos CLI baseline and fix more typos
  .gitattributes
  .github/workflows/typos.yml
  _typos.toml
  bin/zip-plugin.sh
  changelog.txt
Labels: run analysis, run tests

#1847 Update typos toml
  _typos.toml
Labels: run analysis, run tests

#1849 Add more context to typos toml config
  _typos.toml
Labels: run tests

#1851 Fix recaptcha name function is returning empty string
  classes/models/FrmRecaptchaSettings.php
Labels: run analysis, run tests

#1852 Add changelog for v6.11.1
  changelog.txt
  readme.txt
Labels: run analysis, run tests

#1853 Show new pill beside payments menu item
  stripe/controllers/FrmTransLitePaymentsController.php
Labels: run analysis, run tests

#1768 Convertkit addon education
  classes/controllers/FrmFormActionsController.php
  classes/views/frm-form-actions/default_actions.php
  images/icons.svg
Labels: run analysis, deploy, run tests

#1850 Add condition checks before registering popper script
  changelog.txt
  classes/controllers/FrmAppController.php
  readme.txt
Labels: run analysis, run tests

#1854 Prepare for v6.11.1
  classes/controllers/FrmAddonsController.php
  classes/helpers/FrmAppHelper.php
  classes/models/FrmRecaptchaSettings.php
  formidable.php
  languages/formidable.pot
  stripe/controllers/FrmTransLitePaymentsController.php
Labels: run analysis, run tests

#1796 Lite changes required for new abandonment stats in monthly email
  classes/models/FrmEmailStats.php
  classes/views/summary-emails/stats.php
Labels: run analysis, run tests

#1855 Update pot file for v6.11.1 release
  languages/formidable.pot
Labels: run tests

#1856 Update since version
  classes/controllers/FrmAppController.php
Labels: run tests

#1819 Add a condition to displaying name your form modal
  js/formidable_admin.js
Labels: run analysis, run tests

#1857 Clean up `FrmAppHelper::is_true` function
  classes/helpers/FrmAppHelper.php
Labels: run analysis, run tests

#1859 Add missing textdomain
  js/formidable_admin.js
Labels: run tests

#1861 Translate ranking field upsell message
  classes/models/FrmField.php
  languages/formidable.pot
Labels: run tests

#1860 Fix: Onboarding Wizard Page PHP Warning Error for PRO Basic License
  classes/controllers/FrmOnboardingWizardController.php
Labels: action: needs qa, run analysis, run tests

#1862 Simplify preview note in Visual Styler
  classes/helpers/FrmStylesPreviewHelper.php
Labels: run analysis, run tests

#1872 Drop old deprecated view files
  classes/views/frm-entries/sidebar-show.php
  classes/views/frm-fields/radio.php
  classes/views/frm-fields/show-build.php
  classes/views/frm-forms/_embed_form_icons.php
  classes/views/frm-forms/create-template-from-an-existing-form.php
  classes/views/frm-forms/list-template.php
  classes/views/frm-forms/list-templates.php
  classes/views/frm-forms/multiselect-accessibility.php
  classes/views/frm-forms/new-form-overlay/code-from-email.php
  classes/views/frm-forms/new-form-overlay/upgrade-body.php
  classes/views/frm-forms/new.php
  classes/views/frm-forms/sidebar-settings.php
  classes/views/frm-settings/recaptcha.php
  classes/views/styles/_upsell-multiple-styles.php
  classes/views/styles/header-buttons.php
Labels: run analysis, run tests

#1870 Translate Payments submenu page title
  stripe/controllers/FrmTransLitePaymentsController.php
Labels: run analysis, run tests

#1858 redirect to a URL after submitting form
  tests/cypress/e2e/Forms/formsSettings.cy.js
  tests/cypress/support/commands.js
Labels: run analysis, run tests

#1875 Fix entries list appears empty when item meta with 0 field ID exists
  classes/helpers/FrmEntriesListHelper.php
Labels: run analysis, run tests

#1868 Translate upsell popup messages
  classes/models/FrmField.php
  languages/formidable.pot
Labels: run analysis, run tests

#1865 Fix issue with enabling draft button after lookup is finished
  js/formidable.js
Labels: run analysis, run tests

#1874 Exclude repeater forms and entries from summary email
  classes/helpers/FrmEmailSummaryHelper.php
Labels: run analysis, run tests

#1841 Remove width limit from h1 title
  css/frm_admin.css
Labels: run tests

#1880 Fix pr 1866 formatting
  classes/models/FrmEntryValidate.php
Labels: run analysis, run tests

#1879 Modify wp.org Banner
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
Labels: run analysis, run tests

#1882 Fix issue 1881 / pass $filter_args to frm_trigger_create_action filter
  classes/controllers/FrmFormActionsController.php
Labels: run analysis, run tests

#1878 add more accessibility test coverage and update existing tests
  package-lock.json
  package.json
  tests/cypress/e2e/Entries/doNotStoreEntries.cy.js
  tests/cypress/e2e/Forms/bulkDeleteForms.cy.js
  tests/cypress/e2e/Forms/duplicateForm.cy.js
  tests/cypress/e2e/Forms/fieldsInFormBuilder.cy.js
  tests/cypress/e2e/Forms/formsSettings.cy.js
  tests/cypress/e2e/GlobalSettings/globalSettingsUpdates.cy.js
  tests/cypress/e2e/admin-a11y.cy.js
Labels: run analysis, run tests

#1887 Add screen reader label for form dropdown filter
  classes/helpers/FrmEntriesListHelper.php
  languages/formidable.pot
  tests/cypress/e2e/admin-a11y.cy.js
Labels: run analysis, run tests

#1888 Update error handling when viewing an entry that does not exist
  classes/controllers/FrmEntriesController.php
Labels: run analysis, run tests

#1886 Fix International Phone Field Validation Issue
  js/formidable.js
Labels: action: needs qa, run analysis, run tests

#1863 Hide submit field button from field search result
  css/frm_admin.css
Labels: run analysis, run tests

#1890 Pro issue 5203
  classes/controllers/FrmFieldsController.php
  classes/helpers/FrmAppHelper.php
  classes/models/FrmField.php
  psalm.xml
Labels: run analysis, run tests

#1884 Update changelog for 6.11.2
  changelog.txt
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormActionsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmEntriesListHelper.php
  classes/models/FrmField.php
  classes/models/fields/FrmFieldType.php
  readme.txt
Labels: run analysis, run tests

#1891 Prepare for v6.11.2
  classes/helpers/FrmAppHelper.php
  formidable.php
  js/formidable.min.js
  languages/formidable.pot
Labels: run analysis, run tests

#1892 Small grammar fix in changelog
  changelog.txt
  readme.txt
Labels: run tests

#1877 Trigger a new action hook after field is deleted
  js/formidable_admin.js
Labels: run tests

#1867 Make license messages translatable
  classes/helpers/FrmAppHelper.php
  classes/views/frm-settings/license_box.php
Labels: run analysis, run tests
