Repository Strategy11/formidable-forms, pull requests merged in 2024-03, with the labels that each got.

#1517 Reduce server load and page load times
  classes/controllers/FrmAddonsController.php
  classes/models/FrmAddon.php
  classes/models/FrmApplicationApi.php
  classes/models/FrmFormApi.php
  classes/models/FrmFormTemplateApi.php
  classes/models/FrmStyleApi.php
  classes/models/FrmYoutubeFeedApi.php
  classes/views/form-templates/template.php
  tests/misc/test_FrmAddon.php
Labels: action: needs qa, run analysis

#1550 Only make frm_has_shortcodes children spans display block fix
  css/frm_admin.css
Labels: run analysis

#1511 Include term_parent in exported xml
  classes/controllers/FrmXMLController.php
  classes/views/xml/posts_xml.php
Labels: run analysis

#1547 New function `FrmForm::prepare_form_row_data`
  classes/models/FrmForm.php
  tests/forms/test_FrmForm.php
Labels: run analysis

#1520 Ranking Field
  classes/controllers/FrmStylesController.php
  classes/helpers/FrmFieldsHelper.php
  classes/models/FrmField.php
  classes/models/FrmStyle.php
  classes/models/fields/FrmFieldType.php
  classes/views/frm-fields/single-option.php
  classes/views/shared/upgrade_overlay.php
  css/admin/style.css
  css/custom_theme.css.php
  css/frm_admin.css
  fonts/s11-fp.svg
  images/icons.svg
  images/ranking-field.svg
  js/formidable.js
  js/formidable_admin.js
Labels: run analysis

#1555 Fix Alignment and Button Styles on Add-Ons Page
  css/frm_admin.css
Labels: action: needs qa, run analysis

#1557 Prepare for release
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmStylesController.php
  classes/controllers/FrmXMLController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmStylesHelper.php
  classes/helpers/FrmXMLHelper.php
  classes/models/FrmAddon.php
  classes/models/FrmField.php
  classes/models/FrmForm.php
  classes/models/FrmFormApi.php
  classes/models/fields/FrmFieldHTML.php
  classes/models/fields/FrmFieldType.php
  formidable.php
  js/formidable.min.js
  languages/formidable.pot
Labels: run analysis

#1553 Turnstile
  classes/factories/FrmCaptchaFactory.php
  classes/models/FrmField.php
  classes/models/FrmFieldCaptchaSettings.php
  classes/models/FrmHcaptchaSettings.php
  classes/models/FrmRecaptchaSettings.php
  classes/models/FrmSettings.php
  classes/models/FrmTurnstileSettings.php
  classes/models/fields/FrmFieldCaptcha.php
  classes/models/fields/FrmFieldType.php
  classes/views/frm-fields/back-end/field-captcha.php
  classes/views/frm-fields/back-end/settings.php
  classes/views/frm-settings/captcha/captcha.php
  classes/views/frm-settings/captcha/captcha_keys.php
  css/frm_admin.css
  images/turnstile.gif
  js/formidable_admin.js
Labels: action: needs qa

#1560 Turnstile phpcs fixes
  classes/models/FrmFieldCaptchaSettings.php
  classes/models/FrmRecaptchaSettings.php
  classes/models/FrmSettings.php
Labels: run analysis

#1559 Set fields updated to 0 on global settings form submit
  js/formidable_admin.js
Labels: run analysis

#1566 add new filter that will support enabling the Bulk Edit Options, fix …
  classes/controllers/FrmFieldsController.php
  classes/views/frm-fields/single-option.php
Labels: run analysis

#1475 Prevent null from being passed to string functions
  classes/helpers/FrmAppHelper.php
  tests/misc/test_FrmAppHelper.php
Labels: run analysis, action: needs tests

#1577 Skip sending monthly summary email if there is no entries
  classes/models/FrmEmailMonthly.php
Labels: run analysis

#1567 Add an action hook that fires after csv is generated
  classes/helpers/FrmCSVExportHelper.php
Labels: run analysis

#1545 do frm_after_field_is_imported action even if form exists
  classes/helpers/FrmXMLHelper.php
Labels: run analysis

#1552 use button for draft trigger
  classes/helpers/FrmFormsHelper.php
  js/formidable.js
Labels: run analysis

#1556 Reset hcaptcha when navigating pages and switch to explicit rendering
  classes/models/fields/FrmFieldCaptcha.php
  js/formidable.js
Labels: deploy

#1586 Add checks if set time limit function exists before calling it
  classes/controllers/FrmXMLController.php
  stripe/helpers/FrmStrpLiteConnectHelper.php
Labels: run analysis

#1587 Use a less generic id in floating links icon fix
  classes/views/frm-settings/captcha/captcha.php
  js/packages/floating-links/config.js
Labels: deploy

#1563 Inbox slidein
  classes/controllers/FrmAppController.php
  classes/helpers/FrmAppHelper.php
  classes/models/FrmInbox.php
  classes/views/inbox/banner.php
  classes/views/shared/review.php
  css/frm_admin.css
  css/packages/s11-floating-links.css
  js/formidable_admin.js
  js/packages/floating-links/s11-floating-links.js
Labels: action: needs qa, run analysis

#1588 Use card styling for review request
  classes/views/shared/review.php
  css/frm_admin.css
  css/packages/s11-floating-links.css
  js/admin/dom.js
  js/packages/floating-links/s11-floating-links.js
Labels: run analysis

#1594 Prepare for 6.8.4
  classes/controllers/FrmAppController.php
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmInboxController.php
  classes/factories/FrmCaptchaFactory.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmCSVExportHelper.php
  classes/helpers/FrmXMLHelper.php
  classes/models/FrmEmailMonthly.php
  classes/models/FrmFieldCaptchaSettings.php
  classes/models/FrmHcaptchaSettings.php
  classes/models/FrmInbox.php
  classes/models/FrmRecaptchaSettings.php
  classes/models/FrmTurnstileSettings.php
  classes/models/fields/FrmFieldCaptcha.php
  classes/models/fields/FrmFieldType.php
  formidable.php
  js/formidable.min.js
  languages/formidable.pot
Labels: run analysis

#1595 Fix fatal error when styles API request fails
  classes/models/FrmAddon.php
  classes/views/styles/_styles-list.php
Labels: run analysis
