Repository Strategy11/formidable-forms, pull requests merged in 2024-10, with the labels that each got.

#2012 Cypress test update for add-ons page
  classes/views/form-templates/list.php
  js/admin/style.js
  tests/cypress/e2e/Form Templates/FormTemplates.cy.js
  tests/cypress/e2e/admin-a11y.cy.js
Labels: run analysis, run tests

#1919 Collect feedback deactivation
  classes/controllers/FrmDeactivationFeedbackController.php
  classes/controllers/FrmHooksController.php
  css/admin/deactivation-feedback.css
  js/admin/deactivation-feedback.js
Labels: action: needs qa, run analysis, deploy, run tests

#2005 Add css classes to summary field
  classes/models/FrmFieldFormHtml.php
Labels: run analysis, run tests

#2015 Revert "Add css classes to summary field"
  classes/models/FrmFieldFormHtml.php
Labels: run analysis, run tests

#1963 add-ons page validations
  tests/cypress/e2e/Add-Ons/validateAddOnsPage.cy.js
Labels: run analysis, run tests

#2018 Add type check to avoid php warning
  classes/controllers/FrmSimpleBlocksController.php
Labels: run analysis, run tests

#2010 Adapt `FrmEmailSummary` to support `FrmAIEmailCreditAlert`
  classes/models/FrmEmailSummary.php
Labels: run analysis, run tests

#2019 Build scripts
  js/addons-page.js
  js/form-templates.js
  js/formidable_blocks.js
  js/formidable_dashboard.js
  js/formidable_overlay.js
  js/formidable_styles.js
  js/onboarding-wizard.js
Labels: run analysis, run tests

#2013 Fix default email setting is never used
  classes/helpers/FrmFieldsHelper.php
  classes/views/frm-form-actions/email_action.php
Labels: action: needs qa, run analysis, run tests

#2020 Pro issue 5404 / Black friday
  classes/controllers/FrmAppController.php
  css/admin/frm_admin_global.css
Labels: run analysis, run tests

#2028 Remove lite upgrade page in plugin
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmAppController.php
  classes/views/addons/upgrade_to_pro.php
  css/frm_admin.css
  tests/cypress/e2e/admin-a11y.cy.js
Labels: run analysis, run tests

#2023 validations for applications page
  classes/models/FrmApplicationTemplate.php
  tests/cypress/e2e/Applications/validateApplicationsPage.cy.js
Labels: run analysis, run tests

#2035 dynamic count handling on add-ons page
  tests/cypress/e2e/Add-Ons/validateAddOnsPage.cy.js
Labels: run analysis, run tests

#2037 Fix white div at the bottom of plugins page
  classes/controllers/FrmDeactivationFeedbackController.php
Labels: run analysis, run tests

#2032 Fix style class copy error
  js/addons-page.js
  js/form-templates.js
  js/formidable_blocks.js
  js/formidable_dashboard.js
  js/formidable_overlay.js
  js/formidable_styles.js
  js/onboarding-wizard.js
  js/src/admin/styles.js
Labels: run analysis, run tests

#2038 Drop old vendor prefix webkit clip path
  css/admin/deactivation-feedback.css
  css/frm_grids.css
Labels: run analysis, run tests

#2039 Drop old clip css
  css/admin/deactivation-feedback.css
  css/frm_grids.css
Labels: run analysis, run tests

#2040 Add first activation option
  classes/models/FrmInbox.php
  classes/models/FrmMigrate.php
Labels: run analysis, run tests

#2031 Fix some add-ons icons appearing greyed out
  css/admin/addons-page.css
Labels: run analysis, run tests

#2041 Make tooltip icon color used in shortcode inputs consistent
  css/frm_admin.css
Labels: run analysis, run tests

#2045 Remove IE notice
  classes/helpers/FrmAppHelper.php
Labels: run analysis, run tests

#2044 Update kit branding
  classes/helpers/FrmAddonsHelper.php
  classes/views/frm-form-actions/default_actions.php
  images/icons.svg
Labels: run analysis, run tests

#2048 Fix pro issue 5427
  js/formidable.js
Labels: run analysis, run tests

#2047 update failing tests
  tests/cypress/e2e/Add-Ons/validateAddOnsPage.cy.js
  tests/cypress/e2e/Applications/validateApplicationsPage.cy.js
  tests/cypress/e2e/Form Templates/FormTemplates.cy.js
  tests/cypress/e2e/Forms/formPageDataValidation.cy.js
Labels: run analysis, run tests

#2046 Redirect immediately to onboarding when activating a single plugin
  classes/controllers/FrmOnboardingWizardController.php
Labels: run analysis, run tests

#2056 Get cypress passing
  classes/controllers/FrmAppController.php
  classes/controllers/FrmOnboardingWizardController.php
  cypress.config.js
  js/packages/floating-links/s11-floating-links.js
  tests/cypress/e2e/Applications/validateApplicationsPage.cy.js
Labels: run analysis, run tests

#2051 Fix Campaign Monitor icon color inconsistency in global settings menu
  css/admin/addons-page.css
  images/icons.svg
Labels: run analysis, run tests

#2006 Change the UI/UX of conditional logic elements
  css/frm_admin.css
Labels: run analysis, run tests

#2029 Fix pro issue 5410 / Use more descriptive names for name field subfie…
  classes/models/fields/FrmFieldName.php
Labels: run analysis, run tests

#2059 Drop deprecated support for string where value in generate_query_stri…
  classes/models/FrmDb.php
Labels: run analysis, run tests

#2060 Stop using left outer join for meta query
  classes/models/FrmEntryMeta.php
Labels: run analysis, run tests

#2054 improve primary color from quick settings style editor
  classes/helpers/FrmStylesHelper.php
  classes/views/styles/_quick-settings.php
  classes/views/styles/_style-options.php
  css/admin/style-components.css
Labels: run analysis, run tests

#2058 Try to render captcha a second time on a timeout
  js/formidable.js
Labels: run analysis, run tests

#2062 Drop IP warning from settings
  classes/controllers/FrmAppController.php
  classes/models/FrmSettings.php
Labels: run analysis, run tests

#2064 Drop more inbox page code
  classes/controllers/FrmInboxController.php
  classes/views/frm-form-actions/_email_settings.php
  js/formidable_admin.js
Labels: run analysis, run tests

#2034 [I18n] Fix issues and add improvements to JavaScript internationalization
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmAppController.php
  classes/models/FrmReviews.php
  js/admin/applications.js
  js/admin/embed.js
  js/admin/style.js
  js/formidable_admin.js
  stripe/helpers/FrmTransLiteListHelper.php
Labels: run analysis, run tests

#2066 Fix invalid doing it wrong message
  stripe/models/FrmStrpLitePaymentTypeHandler.php
Labels: run analysis, run tests

#2011 add "for" accessibility to style editor elements, add form descriptio…
  classes/helpers/FrmStylesHelper.php
  classes/views/styles/_buttons.php
  classes/views/styles/_check-box-radio-fields.php
  classes/views/styles/_field-colors.php
  classes/views/styles/_field-description.php
  classes/views/styles/_field-labels.php
  classes/views/styles/_field-sizes.php
  classes/views/styles/_form-description.php
  classes/views/styles/_form-messages.php
  classes/views/styles/_form-title.php
  classes/views/styles/_general.php
  classes/views/styles/_quick-settings.php
Labels: action: needs qa, run analysis, run tests

#2068 Avoid sending test emails to AC
  classes/controllers/FrmOnboardingWizardController.php
Labels: run analysis, run tests

#2071 Fix redirect issues for upgrade and black friday
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmAppController.php
Labels: run analysis, run tests

#2072 Prepare for 6.16
  changelog.txt
  classes/controllers/FrmAppController.php
  classes/controllers/FrmInboxController.php
  classes/controllers/FrmOnboardingWizardController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/helpers/FrmStylesHelper.php
  classes/models/FrmApplicationTemplate.php
  classes/models/FrmInbox.php
  classes/models/FrmInstallPlugin.php
  classes/models/fields/FrmFieldName.php
  classes/views/addons/upgrade_to_pro.php
  formidable.php
  js/addons-page.js
  js/form-templates.js
  js/formidable.min.js
  js/formidable.min.js.map
  js/formidable_blocks.js
  js/formidable_dashboard.js
  js/formidable_overlay.js
  js/formidable_styles.js
  languages/formidable.pot
  readme.txt
Labels: run analysis, run tests

#2074 Check for null in sanitize_embedded_shortcodes
  classes/helpers/FrmFieldsHelper.php
Labels: run analysis, run tests

#2073 Disable form CSS in visual styler more safely
  classes/controllers/FrmStylesController.php
Labels: run analysis, run tests

#2075 Add "NEW" to payment field
  classes/views/frm-forms/add_field_links.php
  css/frm_admin.css
Labels: run analysis, run tests

#2067 Add a check for current form name (no title) to show the form name modal
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFormsHelper.php
  classes/helpers/FrmFormsListHelper.php
  classes/views/frm-entries/direct.php
  classes/views/styles/_manage-styles-row.php
  classes/views/xml/import_form.php
  classes/widgets/FrmElementorWidget.php
  js/formidable_admin.js
Labels: run analysis, run tests

#2022 add the missing name attribute to independent slider fields
  classes/views/styles/components/templates/slider.php
Labels: action: needs qa, run analysis, run tests

#2077 Also send name when subscribing to active campaign
  classes/controllers/FrmOnboardingWizardController.php
Labels: run analysis, run tests
