Repository Strategy11/formidable-forms, pull requests merged in 2024-09, with the labels that each got.

#1962 Drop textdomain for common WP string
  classes/helpers/FrmOnSubmitHelper.php
  phpcs.xml
  stripe/models/FrmTransLiteAction.php
Labels: run analysis, run tests

#1883 Fix NEW style for Payments item when hovering over the formidable admin menu.
  css/admin/frm_admin_global.css
Labels: run analysis, run tests

#1958 Enhance error messages in Visual Styler page
  classes/controllers/FrmStylesController.php
Labels: run analysis, run tests

#1935 Update types
  classes/controllers/FrmEntriesController.php
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmFormActionsController.php
  classes/controllers/FrmFormsController.php
  classes/controllers/FrmHooksController.php
  classes/controllers/FrmStylesController.php
  classes/factories/FrmFieldFactory.php
  classes/helpers/FrmListHelper.php
  classes/models/FrmForm.php
  classes/models/FrmFormAction.php
  classes/models/FrmFormMigrator.php
  classes/models/FrmInstallerSkin.php
  classes/views/frm-fields/back-end/settings.php
  phpcs.xml
  phpstan.neon
  psalm.xml
  stripe/controllers/FrmStrpLiteHooksController.php
  stripe/controllers/FrmTransLiteHooksController.php
  stripe/models/FrmTransLiteAction.php
Labels: run analysis, run tests

#1966 Add type comments to xml helper
  classes/helpers/FrmXMLHelper.php
Labels: run analysis, run tests

#1953 Checkbox and Radio Button Style Issues After New Style Update
  css/custom_theme.css.php
Labels: action: needs qa, run analysis, run tests

#1968 Do not pass non-customizable fields to Akismet guest info
  classes/models/FrmEntryValidate.php
Labels: run tests

#1970 Drop unused var/db query for all templates
  classes/controllers/FrmFormsController.php
  phpstan.neon
  rector.php
Labels: run analysis, run tests

#1971 Add stubs for cache plugins
  phpstan.neon
  stubs.php
Labels: run analysis, run tests

#1972 Reduce file scope of some phpstan exceptions
  phpstan.neon
Labels: run analysis, run tests

#1973 Revert "Support fields validation with captcha"
  js/formidable.js
Labels: run tests

#1969 Start working on readme/changelog for v6.14
  changelog.txt
  readme.txt
Labels: run analysis, run tests

#1974 Issue fixes/ff style update
  classes/views/styles/_buttons.php
  classes/views/styles/_general.php
  classes/views/styles/_styles-edit.php
  classes/views/styles/components/templates/background-image.php
  js/admin/style.js
  js/formidable_dashboard.js.map
  js/formidable_styles.js
  js/formidable_styles.js.map
  js/src/admin/styles/slider-style-component.js
Labels: run analysis, run tests

#1975 Prepare for 6.14
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/helpers/FrmStylesHelper.php
  classes/helpers/FrmStylesPreviewHelper.php
  classes/models/FrmStyle.php
  classes/views/styles/components/FrmAlignStyleComponent.php
  classes/views/styles/components/FrmBackgroundImageStyleComponent.php
  classes/views/styles/components/FrmColorpickerStyleComponent.php
  classes/views/styles/components/FrmDirectionStyleComponent.php
  classes/views/styles/components/FrmDropdownStyleComponent.php
  classes/views/styles/components/FrmFieldShapeStyleComponent.php
  classes/views/styles/components/FrmPrimaryColorStyleComponent.php
  classes/views/styles/components/FrmSliderStyleComponent.php
  classes/views/styles/components/FrmStyleComponent.php
  classes/views/styles/components/templates/background-image.php
  formidable.php
  js/form-templates.js
  js/formidable.min.js
  js/formidable_blocks.js
  js/formidable_styles.js
  languages/formidable.pot
Labels: run analysis, run tests

#1978 Include (first) and (last) when mapping name fields to stripe lite actions
  stripe/models/FrmTransLiteAction.php
Labels: run analysis, run tests

#1977 Fix missing checkbox marker in backend
  css/custom_theme.css.php
  css/frm_admin.css
Labels: action: needs qa, run analysis, run tests

#1981 Fix pro issue 5367 / add redirects to visual views upsell and index p…
  classes/controllers/FrmEntriesController.php
Labels: run analysis, run tests

#1960 Move Styles & Scripts settings to Manage Styles tab
  classes/controllers/FrmStylesController.php
  classes/views/frm-settings/general.php
  classes/views/styles/manage.php
Labels: run analysis, run tests

#1984 Add type comments
  classes/helpers/FrmFieldsHelper.php
Labels: run analysis, run tests

#1979 Fix HTML display issue for checkbox with text and links
  css/custom_theme.css.php
Labels: action: needs qa, run analysis, run tests

#1988 Fix: Radio button theme conflict issue
  css/custom_theme.css.php
Labels: run analysis, run tests

#1987 Skip rendering captcha only if closest form is hidden
  js/formidable.js
Labels: run analysis, run tests

#1982 fix error fields style when underline is used as field shape type
  classes/helpers/FrmStylesHelper.php
  classes/models/FrmStyle.php
  classes/views/styles/_field-colors.php
  classes/views/styles/_quick-settings.php
  classes/views/styles/components/FrmSliderStyleComponent.php
  classes/views/styles/components/FrmStyleComponent.php
  classes/views/styles/components/templates/slider.php
  css/_single_theme.css.php
  css/admin/style-components.css
  js/form-templates.js.map
  js/formidable_dashboard.js.map
  js/formidable_overlay.js.map
  js/formidable_styles.js
  js/formidable_styles.js.map
  js/onboarding-wizard.js.map
  js/src/admin/styles/slider-style-component.js
Labels: action: needs qa, run analysis, run tests

#1989 Fix pro issue 5364
  classes/models/FrmField.php
  classes/models/FrmFieldFormHtml.php
Labels: run analysis, run tests

#1983 Start working on readme for 6.14.1
  changelog.txt
  readme.txt
Labels: run analysis, run tests

#1991 Change box shadow styler setting back to Remove Box Shadow
  classes/views/styles/_field-colors.php
Labels: run analysis, run tests

#1992 Prepare for v6.14.1
  changelog.txt
  classes/controllers/FrmEntriesController.php
  classes/helpers/FrmAppHelper.php
  formidable.php
  js/formidable.min.js
  languages/formidable.pot
  readme.txt
Labels: run analysis, run tests

#1997 Add utm content to upgrade ctas
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmDashboardHelper.php
  classes/views/dashboard/templates/pro-features-list.php
  classes/views/frm-settings/license_box.php
Labels: run analysis, run tests

#1998 Fix cypress upgrade link check
  tests/cypress/e2e/Forms/formPageDataValidation.cy.js
Labels: run analysis, run tests

#2000 Fix cut-off issue for Pro upgrade CTA at the bottom of the global settings page
  css/frm_admin.css
Labels: run analysis, run tests

#2001 Prefer method over function when calling doing it wrong
  classes/helpers/FrmCurrencyHelper.php
  classes/helpers/FrmFieldsHelper.php
  classes/models/FrmEntryValidate.php
  stripe/models/FrmStrpLitePaymentTypeHandler.php
  stripe/models/FrmTransLiteDb.php
Labels: run analysis, run tests

#1995 Do not validate confirmation field when main field loses focus
  js/formidable.js
Labels: action: needs qa, run analysis, run tests

#1993 Hide all admin notices that wasn't added by our code (core and addons) from our pages
  classes/controllers/FrmAppController.php
  classes/controllers/FrmHooksController.php
  css/frm_admin.css
Labels: action: needs qa, run analysis, run tests

#1999 Fix pro issue 5064 / Fix format unslashing issue in field cache
  classes/models/FrmField.php
Labels: action: needs qa, run analysis, run tests

#1967 Add Default from address setting
  classes/controllers/FrmOnboardingWizardController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmEmailHelper.php
  classes/models/FrmEmail.php
  classes/models/FrmEmailSummary.php
  classes/models/FrmSettings.php
  classes/views/form-templates/modals/code-from-email-modal.php
  classes/views/form-templates/modals/leave-email-modal.php
  classes/views/frm-settings/general.php
  classes/views/onboarding-wizard/steps/default-email-address-step.php
  classes/views/onboarding-wizard/steps/install-formidable-pro-step.php
  js/form-templates.js
  js/formidable_blocks.js
  js/formidable_styles.js
  js/onboarding-wizard.js
  js/src/onboarding-wizard/elements/getDOMElements.js
  js/src/onboarding-wizard/events/setupEmailStepButtonListener.js
  js/src/onboarding-wizard/ui/showError.js
Labels: action: needs qa, run analysis, deploy, run tests

#2007 Allow field search to also match plural
  js/formidable_admin.js
Labels: action: needs qa, run analysis, run tests

#1985 form templates functionalities
  tests/cypress/e2e/Form Templates/FormTemplates.cy.js
Labels: run analysis, run tests
