Repository Strategy11/formidable-forms, pull requests merged in 2025-01, with the labels that each got.

#2196 Add check for input var
  js/formidable.js
Labels: run analysis, run tests

#2197 Add form_id type index to fields table
  classes/helpers/FrmAppHelper.php
  classes/models/FrmMigrate.php
Labels: run analysis, run tests

#2198 Optimize field type queries
  classes/models/FrmField.php
Labels: run analysis, run tests

#2199 Optimize field queries
  classes/models/FrmField.php
Labels: run analysis, run tests

#2201 Fix broken e2e tests
  classes/controllers/FrmEntriesController.php
Labels: run analysis, run tests

#2202 Fix issue with entries page when inbox badge is disabled
  classes/controllers/FrmEntriesController.php
Labels: run analysis, run tests

#2204 Add CSV export batch size filter and optimize entries query when Pro is not installed
  classes/helpers/FrmCSVExportHelper.php
Labels: run analysis, run tests

#2203 Dashboard Inbox doesn't refresh properly
  classes/controllers/FrmInboxController.php
  classes/models/FrmAddon.php
  classes/models/FrmInbox.php
  classes/views/form-templates/modals/leave-email-modal.php
  tests/cypress/e2e/Form Templates/FormTemplates.cy.js
Labels: action: needs qa, run analysis, run tests

#2195 Fix centered submit button bottom margin value with modern dark theme
  classes/helpers/FrmStylesHelper.php
  css/_single_theme.css.php
  tests/phpunit/styles/test_FrmStylesHelper.php
Labels: run analysis, run tests

#2210 Add utf8 with bom csv export option
  classes/helpers/FrmCSVExportHelper.php
Labels: run analysis, run tests

#2117 Add redirect delay settings
  classes/controllers/FrmFormsController.php
  classes/helpers/FrmOnSubmitHelper.php
  classes/models/FrmOnSubmitAction.php
  classes/views/frm-form-actions/on_submit_redirect_settings.php
  css/frm_admin.css
  js/formidable.js
  js/formidable_admin.js
Labels: run analysis, deploy, run tests

#2206 Improve email validation
  classes/models/fields/FrmFieldEmail.php
Labels: run analysis, run tests

#2214 Fix missing latest entries on dashboard
  classes/controllers/FrmDashboardController.php
  classes/controllers/FrmEntriesController.php
  classes/helpers/FrmEntriesHelper.php
Labels: run analysis, run tests

#2173 Lite to pro improvement
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmAppController.php
  classes/controllers/FrmDashboardController.php
  classes/controllers/FrmHooksController.php
  classes/controllers/FrmSettingsController.php
  classes/helpers/FrmAddonsHelper.php
  classes/helpers/FrmFormTemplatesHelper.php
  classes/helpers/FrmTipsHelper.php
  classes/views/dashboard/templates/pro-features-list.php
  classes/views/frm-settings/form.php
  classes/views/frm-settings/settings_cta.php
  classes/views/shared/admin-cta.php
  classes/views/shared/views-info.php
  css/admin/applications.css
  css/admin/dashboard.css
  css/frm_admin.css
  images/applications/custom-applications.svg
  images/applications/folder.svg
  images/guarantee.svg
  images/star.svg
  images/views-info/wordpress.png
  js/admin/applications.js
  tests/cypress/e2e/Applications/validateApplicationsPage.cy.js
Labels: run analysis, deploy, run tests

#2213 fix failling unit test in php 7.4
  classes/controllers/FrmFormsController.php
Labels: run analysis, run tests

#2212 Update readme for v6.17
  changelog.txt
  readme.txt
Labels: run tests

#2216 Unset empty response content
  classes/controllers/FrmFormsController.php
Labels: run analysis, run tests

#2205 New sales API
  classes/controllers/FrmAddonsController.php
  classes/controllers/FrmAppController.php
  classes/helpers/FrmApiHelper.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmDashboardHelper.php
  classes/models/FrmAddon.php
  classes/models/FrmInbox.php
  classes/models/FrmSalesAPI.php
  classes/views/dashboard/templates/pro-features-list.php
  classes/views/frm-settings/license_box.php
  classes/views/shared/admin-footer-links.php
  phpstan.neon
Labels: run analysis, run tests

#2219 Rename file
  classes/models/FrmSalesApi.php
Labels: run analysis, run tests

#2220 Update deploy workflow
  .github/workflows/push-deploy.yml
Labels: run analysis, run tests

#2221 Fix payments lists empty when inbox count is displayed
  changelog.txt
  readme.txt
  stripe/controllers/FrmTransLiteHooksController.php
  stripe/controllers/FrmTransLiteListsController.php
  stubs.php
Labels: run analysis, run tests

#2223 Remove screen options on entry edit page
  classes/controllers/FrmEntriesController.php
Labels: run analysis, run tests

#2194 Output custom css classes when rendering forms
  classes/controllers/FrmSimpleBlocksController.php
Labels: run analysis, run tests

#2227 Move admin bar global setting to misc
  classes/views/frm-settings/general.php
  classes/views/frm-settings/misc.php
Labels: run analysis, run tests

#2228 Fix response replace is not a function error
  js/formidable.js
Labels: run analysis, run tests

#1986 Address Styling Issues on Entry (Edit/New) and Style Pages
  css/custom_theme.css.php
  css/frm_admin.css
Labels: action: needs qa, run analysis, run tests

#2230 Add url to frm_xml_response filter
  classes/controllers/FrmXMLController.php
Labels: run analysis, run tests

#2231 Remove submit field from payment settings
  stripe/models/FrmTransLiteAction.php
Labels: run analysis, run tests

#2232 Track when message settings changed
  classes/models/FrmUsage.php
Labels: run analysis, run tests

#2233 Drop deprecated file
  stripe/views/payments/entry_sidebar.php
Labels: run analysis, run tests

#2236 Move some phpstan exceptions to problematic files only
  phpstan.neon
Labels: run analysis, run tests

#2237 Fix JS error when searching fields
  js/formidable_admin.js
Labels: run analysis, run tests
