Repository Strategy11/formidable-forms, pull requests merged in 2025-02, with the labels that each got.

#2207 Add error style to checkbox and radio fields when there is error with them
  css/_single_theme.css.php
Labels: run analysis, run tests

#2167 Lite update for applications dropdown
  classes/views/frm-forms/settings-advanced.php
  psalm.xml
Labels: run analysis, run tests

#2211 Avoid selecting text when multiselecting fields
  js/formidable_admin.js
Labels: action: needs qa, run analysis, run tests

#2238 Lite to pro design update
  classes/helpers/FrmAppHelper.php
  css/frm_admin.css
  js/admin/applications.js
Labels: run analysis, deploy, run tests

#2242 Update readme for v6.18
  changelog.txt
  readme.txt
Labels: run analysis, run tests

#2240 Issuefix/ff style
  classes/views/styles/components/FrmSliderStyleComponent.php
  js/form-templates.js.map
  js/formidable_blocks.js.map
  js/formidable_styles.js
  js/formidable_styles.js.map
  js/onboarding-wizard.js.map
  js/src/admin/styles/slider-style-component.js
Labels: action: needs qa, run analysis, run tests

#2244 Fix cypress upgrade bar issue
  tests/cypress/e2e/Forms/formPageDataValidation.cy.js
Labels: run tests

#1864 Lite Version: Add Format Settings
  classes/controllers/FrmAppController.php
  classes/controllers/FrmFieldsController.php
  classes/controllers/FrmSettingsController.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmCurrencyHelper.php
  classes/models/FrmEntryValidate.php
  classes/models/fields/FrmFieldNumber.php
  classes/models/fields/FrmFieldPhone.php
  classes/views/frm-fields/back-end/format-dropdown-options.php
  classes/views/frm-fields/back-end/format-dropdown.php
  classes/views/frm-fields/back-end/phone/phone-type.php
  classes/views/frm-fields/back-end/settings.php
  classes/views/frm-settings/_currency.php
  classes/views/frm-settings/general.php
  css/frm_admin.css
  js/admin/settings.js
  js/formidable_admin.js
  stubs.php
Labels: action: needs qa, run analysis, deploy, run tests

#2245 Lite Version: Fix number field step validation
  classes/models/fields/FrmFieldNumber.php
Labels: run analysis, run tests

#2246 Update since versions for v6.18
  classes/controllers/FrmXMLController.php
  classes/helpers/FrmApiHelper.php
  classes/helpers/FrmAppHelper.php
  classes/helpers/FrmCurrencyHelper.php
  classes/views/frm-fields/back-end/format-dropdown-options.php
  classes/views/frm-fields/back-end/format-dropdown.php
  classes/views/frm-forms/settings-advanced.php
  classes/views/frm-settings/general.php
  formidable.php
  js/formidable.min.js
  js/formidable_styles.js
  languages/formidable.pot
  stripe/models/FrmTransLiteAction.php
Labels: run analysis, run tests

#2247 Add more change log items
  changelog.txt
  readme.txt
Labels: run analysis, run tests

#2209 Prevent duplicating field from breaking field group limit
  js/formidable_admin.js
Labels: run analysis, run tests

#2249 Simplify tab event logic
  classes/models/FrmSettings.php
  js/formidable.js
  psalm.xml
Labels: run analysis, run tests

#2250 Fix deactivation modal overlay doesn't show
  css/frm_admin.css
Labels: run analysis, run tests

#2252 Use less jquery when validating
  js/formidable.js
Labels: run analysis, run tests

#2251 Fix views issue 28
  classes/models/fields/FrmFieldUserID.php
Labels: run analysis, run tests

#2254 Fix turnstile does not properly reset on AJAX error
  js/formidable.js
Labels: run analysis, run tests

#2255 Fix js error when triggering change event on hidden field
  js/formidable.js
Labels: run analysis, run tests

#2256 Fix sales api fallback typo
  classes/controllers/FrmAppController.php
Labels: run analysis, run tests

#2260 Only localize scripts once
  classes/helpers/FrmAppHelper.php
Labels: run analysis, run tests
